// Auto-generated by @tisyn/compiler — do not edit
import { agent, operation } from "@tisyn/agent";
import type { DeclaredAgent, OperationSpec } from "@tisyn/agent";
import type { TisynFn } from "@tisyn/ir";

export function Dom(): DeclaredAgent<{ fill: OperationSpec<{ input: { name: string; value: string } }, void>; click: OperationSpec<{ input: { role: string; name: string } }, void>; pressKey: OperationSpec<{ input: { key: string } }, void>; expectVisible: OperationSpec<{ input: { text: string } }, void>; expectNotVisible: OperationSpec<{ input: { text: string } }, void>; expectDisabled: OperationSpec<{ input: { role: string; name: string } }, void>; expectEnabled: OperationSpec<{ input: { role: string; name: string } }, void>; expectTranscript: OperationSpec<{ input: { messages: string[] } }, void>; expectStatusText: OperationSpec<{ input: { text: string } }, void> }> {
  const id = "dom";
  return agent(id, {
    fill: operation<{ input: { name: string; value: string } }, void>(),
    click: operation<{ input: { role: string; name: string } }, void>(),
    pressKey: operation<{ input: { key: string } }, void>(),
    expectVisible: operation<{ input: { text: string } }, void>(),
    expectNotVisible: operation<{ input: { text: string } }, void>(),
    expectDisabled: operation<{ input: { role: string; name: string } }, void>(),
    expectEnabled: operation<{ input: { role: string; name: string } }, void>(),
    expectTranscript: operation<{ input: { messages: string[] } }, void>(),
    expectStatusText: operation<{ input: { text: string } }, void>(),
  });
}

/**
 * Printed Tisyn IR:
 *
 * Fn([],
 *   Let(
 *     "__discard_0",
 *     Eval("dom.expectStatusText",
 *       Construct({
 *         input: Construct({
 *             text: "Say something"
 *           })
 *       })),
 *     Let(
 *       "__discard_1",
 *       Eval("dom.fill",
 *         Construct({
 *           input: Construct({
 *               name: "Message",
 *               value: "hello"
 *             })
 *         })),
 *       Let(
 *         "__discard_2",
 *         Eval("dom.click",
 *           Construct({
 *             input: Construct({
 *                 role: "button",
 *                 name: "Send"
 *               })
 *           })),
 *         Let(
 *           "__discard_3",
 *           Eval("dom.expectVisible",
 *             Construct({
 *               input: Construct({
 *                   text: "Assistant: Echo: hello"
 *                 })
 *             })),
 *           Eval("dom.expectTranscript",
 *             Construct({
 *               input: Construct({
 *                   messages: Arr(
 *                       "You: hello",
 *                       "Assistant: Echo: hello"
 *                     )
 *                 })
 *             }))
 *         )
 *       )
 *     )
 *   ))
 */
export const basicSendReceiveDom: TisynFn<[], unknown> = {
    "tisyn": "fn",
    "params": [],
    "body": {
      "tisyn": "eval",
      "id": "let",
      "data": {
        "tisyn": "quote",
        "expr": {
          "name": "__discard_0",
          "value": {
            "tisyn": "eval",
            "id": "dom.expectStatusText",
            "data": {
              "tisyn": "eval",
              "id": "construct",
              "data": {
                "tisyn": "quote",
                "expr": {
                  "input": {
                    "tisyn": "eval",
                    "id": "construct",
                    "data": {
                      "tisyn": "quote",
                      "expr": {
                        "text": "Say something"
                      }
                    }
                  }
                }
              }
            }
          },
          "body": {
            "tisyn": "eval",
            "id": "let",
            "data": {
              "tisyn": "quote",
              "expr": {
                "name": "__discard_1",
                "value": {
                  "tisyn": "eval",
                  "id": "dom.fill",
                  "data": {
                    "tisyn": "eval",
                    "id": "construct",
                    "data": {
                      "tisyn": "quote",
                      "expr": {
                        "input": {
                          "tisyn": "eval",
                          "id": "construct",
                          "data": {
                            "tisyn": "quote",
                            "expr": {
                              "name": "Message",
                              "value": "hello"
                            }
                          }
                        }
                      }
                    }
                  }
                },
                "body": {
                  "tisyn": "eval",
                  "id": "let",
                  "data": {
                    "tisyn": "quote",
                    "expr": {
                      "name": "__discard_2",
                      "value": {
                        "tisyn": "eval",
                        "id": "dom.click",
                        "data": {
                          "tisyn": "eval",
                          "id": "construct",
                          "data": {
                            "tisyn": "quote",
                            "expr": {
                              "input": {
                                "tisyn": "eval",
                                "id": "construct",
                                "data": {
                                  "tisyn": "quote",
                                  "expr": {
                                    "role": "button",
                                    "name": "Send"
                                  }
                                }
                              }
                            }
                          }
                        }
                      },
                      "body": {
                        "tisyn": "eval",
                        "id": "let",
                        "data": {
                          "tisyn": "quote",
                          "expr": {
                            "name": "__discard_3",
                            "value": {
                              "tisyn": "eval",
                              "id": "dom.expectVisible",
                              "data": {
                                "tisyn": "eval",
                                "id": "construct",
                                "data": {
                                  "tisyn": "quote",
                                  "expr": {
                                    "input": {
                                      "tisyn": "eval",
                                      "id": "construct",
                                      "data": {
                                        "tisyn": "quote",
                                        "expr": {
                                          "text": "Assistant: Echo: hello"
                                        }
                                      }
                                    }
                                  }
                                }
                              }
                            },
                            "body": {
                              "tisyn": "eval",
                              "id": "dom.expectTranscript",
                              "data": {
                                "tisyn": "eval",
                                "id": "construct",
                                "data": {
                                  "tisyn": "quote",
                                  "expr": {
                                    "input": {
                                      "tisyn": "eval",
                                      "id": "construct",
                                      "data": {
                                        "tisyn": "quote",
                                        "expr": {
                                          "messages": {
                                            "tisyn": "eval",
                                            "id": "array",
                                            "data": {
                                              "tisyn": "quote",
                                              "expr": {
                                                "items": [
                                                  "You: hello",
                                                  "Assistant: Echo: hello"
                                                ]
                                              }
                                            }
                                          }
                                        }
                                      }
                                    }
                                  }
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  } as const;

/**
 * Printed Tisyn IR:
 *
 * Fn([],
 *   Eval("dom.expectStatusText",
 *     Construct({
 *       input: Construct({
 *           text: "Disconnected"
 *         })
 *     })))
 */
export const expectDisconnectedDom: TisynFn<[], unknown> = {
    "tisyn": "fn",
    "params": [],
    "body": {
      "tisyn": "eval",
      "id": "dom.expectStatusText",
      "data": {
        "tisyn": "eval",
        "id": "construct",
        "data": {
          "tisyn": "quote",
          "expr": {
            "input": {
              "tisyn": "eval",
              "id": "construct",
              "data": {
                "tisyn": "quote",
                "expr": {
                  "text": "Disconnected"
                }
              }
            }
          }
        }
      }
    }
  } as const;

/**
 * Printed Tisyn IR:
 *
 * Fn([],
 *   Let(
 *     "__discard_0",
 *     Eval("dom.expectStatusText",
 *       Construct({
 *         input: Construct({
 *             text: "Say something"
 *           })
 *       })),
 *     Let(
 *       "__discard_1",
 *       Eval("dom.fill",
 *         Construct({
 *           input: Construct({
 *               name: "Message",
 *               value: "before restart"
 *             })
 *         })),
 *       Let(
 *         "__discard_2",
 *         Eval("dom.click",
 *           Construct({
 *             input: Construct({
 *                 role: "button",
 *                 name: "Send"
 *               })
 *           })),
 *         Eval("dom.expectVisible",
 *           Construct({
 *             input: Construct({
 *                 text: "Assistant: Echo: before restart"
 *               })
 *           }))
 *       )
 *     )
 *   ))
 */
export const sendBeforeRestartDom: TisynFn<[], unknown> = {
    "tisyn": "fn",
    "params": [],
    "body": {
      "tisyn": "eval",
      "id": "let",
      "data": {
        "tisyn": "quote",
        "expr": {
          "name": "__discard_0",
          "value": {
            "tisyn": "eval",
            "id": "dom.expectStatusText",
            "data": {
              "tisyn": "eval",
              "id": "construct",
              "data": {
                "tisyn": "quote",
                "expr": {
                  "input": {
                    "tisyn": "eval",
                    "id": "construct",
                    "data": {
                      "tisyn": "quote",
                      "expr": {
                        "text": "Say something"
                      }
                    }
                  }
                }
              }
            }
          },
          "body": {
            "tisyn": "eval",
            "id": "let",
            "data": {
              "tisyn": "quote",
              "expr": {
                "name": "__discard_1",
                "value": {
                  "tisyn": "eval",
                  "id": "dom.fill",
                  "data": {
                    "tisyn": "eval",
                    "id": "construct",
                    "data": {
                      "tisyn": "quote",
                      "expr": {
                        "input": {
                          "tisyn": "eval",
                          "id": "construct",
                          "data": {
                            "tisyn": "quote",
                            "expr": {
                              "name": "Message",
                              "value": "before restart"
                            }
                          }
                        }
                      }
                    }
                  }
                },
                "body": {
                  "tisyn": "eval",
                  "id": "let",
                  "data": {
                    "tisyn": "quote",
                    "expr": {
                      "name": "__discard_2",
                      "value": {
                        "tisyn": "eval",
                        "id": "dom.click",
                        "data": {
                          "tisyn": "eval",
                          "id": "construct",
                          "data": {
                            "tisyn": "quote",
                            "expr": {
                              "input": {
                                "tisyn": "eval",
                                "id": "construct",
                                "data": {
                                  "tisyn": "quote",
                                  "expr": {
                                    "role": "button",
                                    "name": "Send"
                                  }
                                }
                              }
                            }
                          }
                        }
                      },
                      "body": {
                        "tisyn": "eval",
                        "id": "dom.expectVisible",
                        "data": {
                          "tisyn": "eval",
                          "id": "construct",
                          "data": {
                            "tisyn": "quote",
                            "expr": {
                              "input": {
                                "tisyn": "eval",
                                "id": "construct",
                                "data": {
                                  "tisyn": "quote",
                                  "expr": {
                                    "text": "Assistant: Echo: before restart"
                                  }
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  } as const;

/**
 * Printed Tisyn IR:
 *
 * Fn([],
 *   Let(
 *     "__discard_0",
 *     Eval("dom.expectStatusText",
 *       Construct({
 *         input: Construct({
 *             text: "Say something"
 *           })
 *       })),
 *     Let(
 *       "__discard_1",
 *       Eval("dom.fill",
 *         Construct({
 *           input: Construct({
 *               name: "Message",
 *               value: "hello"
 *             })
 *         })),
 *       Let(
 *         "__discard_2",
 *         Eval("dom.click",
 *           Construct({
 *             input: Construct({
 *                 role: "button",
 *                 name: "Send"
 *               })
 *           })),
 *         Eval("dom.expectVisible",
 *           Construct({
 *             input: Construct({
 *                 text: "Assistant: Echo: hello"
 *               })
 *           }))
 *       )
 *     )
 *   ))
 */
export const sendFirstMessageDom: TisynFn<[], unknown> = {
    "tisyn": "fn",
    "params": [],
    "body": {
      "tisyn": "eval",
      "id": "let",
      "data": {
        "tisyn": "quote",
        "expr": {
          "name": "__discard_0",
          "value": {
            "tisyn": "eval",
            "id": "dom.expectStatusText",
            "data": {
              "tisyn": "eval",
              "id": "construct",
              "data": {
                "tisyn": "quote",
                "expr": {
                  "input": {
                    "tisyn": "eval",
                    "id": "construct",
                    "data": {
                      "tisyn": "quote",
                      "expr": {
                        "text": "Say something"
                      }
                    }
                  }
                }
              }
            }
          },
          "body": {
            "tisyn": "eval",
            "id": "let",
            "data": {
              "tisyn": "quote",
              "expr": {
                "name": "__discard_1",
                "value": {
                  "tisyn": "eval",
                  "id": "dom.fill",
                  "data": {
                    "tisyn": "eval",
                    "id": "construct",
                    "data": {
                      "tisyn": "quote",
                      "expr": {
                        "input": {
                          "tisyn": "eval",
                          "id": "construct",
                          "data": {
                            "tisyn": "quote",
                            "expr": {
                              "name": "Message",
                              "value": "hello"
                            }
                          }
                        }
                      }
                    }
                  }
                },
                "body": {
                  "tisyn": "eval",
                  "id": "let",
                  "data": {
                    "tisyn": "quote",
                    "expr": {
                      "name": "__discard_2",
                      "value": {
                        "tisyn": "eval",
                        "id": "dom.click",
                        "data": {
                          "tisyn": "eval",
                          "id": "construct",
                          "data": {
                            "tisyn": "quote",
                            "expr": {
                              "input": {
                                "tisyn": "eval",
                                "id": "construct",
                                "data": {
                                  "tisyn": "quote",
                                  "expr": {
                                    "role": "button",
                                    "name": "Send"
                                  }
                                }
                              }
                            }
                          }
                        }
                      },
                      "body": {
                        "tisyn": "eval",
                        "id": "dom.expectVisible",
                        "data": {
                          "tisyn": "eval",
                          "id": "construct",
                          "data": {
                            "tisyn": "quote",
                            "expr": {
                              "input": {
                                "tisyn": "eval",
                                "id": "construct",
                                "data": {
                                  "tisyn": "quote",
                                  "expr": {
                                    "text": "Assistant: Echo: hello"
                                  }
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  } as const;

/**
 * Printed Tisyn IR:
 *
 * Fn([],
 *   Let(
 *     "__discard_0",
 *     Eval("dom.expectStatusText",
 *       Construct({
 *         input: Construct({
 *             text: "Say something"
 *           })
 *       })),
 *     Let(
 *       "__discard_1",
 *       Eval("dom.fill",
 *         Construct({
 *           input: Construct({
 *               name: "Message",
 *               value: "hello"
 *             })
 *         })),
 *       Let(
 *         "__discard_2",
 *         Eval("dom.click",
 *           Construct({
 *             input: Construct({
 *                 role: "button",
 *                 name: "Send"
 *               })
 *           })),
 *         Let(
 *           "__discard_3",
 *           Eval("dom.expectVisible",
 *             Construct({
 *               input: Construct({
 *                   text: "Assistant: Echo: hello"
 *                 })
 *             })),
 *           Let(
 *             "__discard_4",
 *             Eval("dom.fill",
 *               Construct({
 *                 input: Construct({
 *                     name: "Message",
 *                     value: "world"
 *                   })
 *               })),
 *             Let(
 *               "__discard_5",
 *               Eval("dom.click",
 *                 Construct({
 *                   input: Construct({
 *                       role: "button",
 *                       name: "Send"
 *                     })
 *                 })),
 *               Eval("dom.expectVisible",
 *                 Construct({
 *                   input: Construct({
 *                       text: "Assistant: Echo: world"
 *                     })
 *                 }))
 *             )
 *           )
 *         )
 *       )
 *     )
 *   ))
 */
export const sendTwoMessagesDom: TisynFn<[], unknown> = {
    "tisyn": "fn",
    "params": [],
    "body": {
      "tisyn": "eval",
      "id": "let",
      "data": {
        "tisyn": "quote",
        "expr": {
          "name": "__discard_0",
          "value": {
            "tisyn": "eval",
            "id": "dom.expectStatusText",
            "data": {
              "tisyn": "eval",
              "id": "construct",
              "data": {
                "tisyn": "quote",
                "expr": {
                  "input": {
                    "tisyn": "eval",
                    "id": "construct",
                    "data": {
                      "tisyn": "quote",
                      "expr": {
                        "text": "Say something"
                      }
                    }
                  }
                }
              }
            }
          },
          "body": {
            "tisyn": "eval",
            "id": "let",
            "data": {
              "tisyn": "quote",
              "expr": {
                "name": "__discard_1",
                "value": {
                  "tisyn": "eval",
                  "id": "dom.fill",
                  "data": {
                    "tisyn": "eval",
                    "id": "construct",
                    "data": {
                      "tisyn": "quote",
                      "expr": {
                        "input": {
                          "tisyn": "eval",
                          "id": "construct",
                          "data": {
                            "tisyn": "quote",
                            "expr": {
                              "name": "Message",
                              "value": "hello"
                            }
                          }
                        }
                      }
                    }
                  }
                },
                "body": {
                  "tisyn": "eval",
                  "id": "let",
                  "data": {
                    "tisyn": "quote",
                    "expr": {
                      "name": "__discard_2",
                      "value": {
                        "tisyn": "eval",
                        "id": "dom.click",
                        "data": {
                          "tisyn": "eval",
                          "id": "construct",
                          "data": {
                            "tisyn": "quote",
                            "expr": {
                              "input": {
                                "tisyn": "eval",
                                "id": "construct",
                                "data": {
                                  "tisyn": "quote",
                                  "expr": {
                                    "role": "button",
                                    "name": "Send"
                                  }
                                }
                              }
                            }
                          }
                        }
                      },
                      "body": {
                        "tisyn": "eval",
                        "id": "let",
                        "data": {
                          "tisyn": "quote",
                          "expr": {
                            "name": "__discard_3",
                            "value": {
                              "tisyn": "eval",
                              "id": "dom.expectVisible",
                              "data": {
                                "tisyn": "eval",
                                "id": "construct",
                                "data": {
                                  "tisyn": "quote",
                                  "expr": {
                                    "input": {
                                      "tisyn": "eval",
                                      "id": "construct",
                                      "data": {
                                        "tisyn": "quote",
                                        "expr": {
                                          "text": "Assistant: Echo: hello"
                                        }
                                      }
                                    }
                                  }
                                }
                              }
                            },
                            "body": {
                              "tisyn": "eval",
                              "id": "let",
                              "data": {
                                "tisyn": "quote",
                                "expr": {
                                  "name": "__discard_4",
                                  "value": {
                                    "tisyn": "eval",
                                    "id": "dom.fill",
                                    "data": {
                                      "tisyn": "eval",
                                      "id": "construct",
                                      "data": {
                                        "tisyn": "quote",
                                        "expr": {
                                          "input": {
                                            "tisyn": "eval",
                                            "id": "construct",
                                            "data": {
                                              "tisyn": "quote",
                                              "expr": {
                                                "name": "Message",
                                                "value": "world"
                                              }
                                            }
                                          }
                                        }
                                      }
                                    }
                                  },
                                  "body": {
                                    "tisyn": "eval",
                                    "id": "let",
                                    "data": {
                                      "tisyn": "quote",
                                      "expr": {
                                        "name": "__discard_5",
                                        "value": {
                                          "tisyn": "eval",
                                          "id": "dom.click",
                                          "data": {
                                            "tisyn": "eval",
                                            "id": "construct",
                                            "data": {
                                              "tisyn": "quote",
                                              "expr": {
                                                "input": {
                                                  "tisyn": "eval",
                                                  "id": "construct",
                                                  "data": {
                                                    "tisyn": "quote",
                                                    "expr": {
                                                      "role": "button",
                                                      "name": "Send"
                                                    }
                                                  }
                                                }
                                              }
                                            }
                                          }
                                        },
                                        "body": {
                                          "tisyn": "eval",
                                          "id": "dom.expectVisible",
                                          "data": {
                                            "tisyn": "eval",
                                            "id": "construct",
                                            "data": {
                                              "tisyn": "quote",
                                              "expr": {
                                                "input": {
                                                  "tisyn": "eval",
                                                  "id": "construct",
                                                  "data": {
                                                    "tisyn": "quote",
                                                    "expr": {
                                                      "text": "Assistant: Echo: world"
                                                    }
                                                  }
                                                }
                                              }
                                            }
                                          }
                                        }
                                      }
                                    }
                                  }
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  } as const;

/**
 * Printed Tisyn IR:
 *
 * Fn([],
 *   Eval("dom.expectEnabled",
 *     Construct({
 *       input: Construct({
 *           role: "textbox",
 *           name: "Message"
 *         })
 *     })))
 */
export const verifyDefaultSessionEnabledDom: TisynFn<[], unknown> = {
    "tisyn": "fn",
    "params": [],
    "body": {
      "tisyn": "eval",
      "id": "dom.expectEnabled",
      "data": {
        "tisyn": "eval",
        "id": "construct",
        "data": {
          "tisyn": "quote",
          "expr": {
            "input": {
              "tisyn": "eval",
              "id": "construct",
              "data": {
                "tisyn": "quote",
                "expr": {
                  "role": "textbox",
                  "name": "Message"
                }
              }
            }
          }
        }
      }
    }
  } as const;

/**
 * Printed Tisyn IR:
 *
 * Fn([],
 *   Let(
 *     "__discard_0",
 *     Eval("dom.expectTranscript",
 *       Construct({
 *         input: Construct({
 *             messages: Arr(
 *                 "You: before restart",
 *                 "Assistant: Echo: before restart"
 *               )
 *           })
 *       })),
 *     Let(
 *       "__discard_1",
 *       Eval("dom.expectStatusText",
 *         Construct({
 *           input: Construct({
 *               text: "Say something"
 *             })
 *         })),
 *       Let(
 *         "__discard_2",
 *         Eval("dom.fill",
 *           Construct({
 *             input: Construct({
 *                 name: "Message",
 *                 value: "after restart"
 *               })
 *           })),
 *         Let(
 *           "__discard_3",
 *           Eval("dom.click",
 *             Construct({
 *               input: Construct({
 *                   role: "button",
 *                   name: "Send"
 *                 })
 *             })),
 *           Eval("dom.expectVisible",
 *             Construct({
 *               input: Construct({
 *                   text: "Assistant: Echo: after restart"
 *                 })
 *             }))
 *         )
 *       )
 *     )
 *   ))
 */
export const verifyRestoredAndSendAfterRestartDom: TisynFn<[], unknown> = {
    "tisyn": "fn",
    "params": [],
    "body": {
      "tisyn": "eval",
      "id": "let",
      "data": {
        "tisyn": "quote",
        "expr": {
          "name": "__discard_0",
          "value": {
            "tisyn": "eval",
            "id": "dom.expectTranscript",
            "data": {
              "tisyn": "eval",
              "id": "construct",
              "data": {
                "tisyn": "quote",
                "expr": {
                  "input": {
                    "tisyn": "eval",
                    "id": "construct",
                    "data": {
                      "tisyn": "quote",
                      "expr": {
                        "messages": {
                          "tisyn": "eval",
                          "id": "array",
                          "data": {
                            "tisyn": "quote",
                            "expr": {
                              "items": [
                                "You: before restart",
                                "Assistant: Echo: before restart"
                              ]
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          },
          "body": {
            "tisyn": "eval",
            "id": "let",
            "data": {
              "tisyn": "quote",
              "expr": {
                "name": "__discard_1",
                "value": {
                  "tisyn": "eval",
                  "id": "dom.expectStatusText",
                  "data": {
                    "tisyn": "eval",
                    "id": "construct",
                    "data": {
                      "tisyn": "quote",
                      "expr": {
                        "input": {
                          "tisyn": "eval",
                          "id": "construct",
                          "data": {
                            "tisyn": "quote",
                            "expr": {
                              "text": "Say something"
                            }
                          }
                        }
                      }
                    }
                  }
                },
                "body": {
                  "tisyn": "eval",
                  "id": "let",
                  "data": {
                    "tisyn": "quote",
                    "expr": {
                      "name": "__discard_2",
                      "value": {
                        "tisyn": "eval",
                        "id": "dom.fill",
                        "data": {
                          "tisyn": "eval",
                          "id": "construct",
                          "data": {
                            "tisyn": "quote",
                            "expr": {
                              "input": {
                                "tisyn": "eval",
                                "id": "construct",
                                "data": {
                                  "tisyn": "quote",
                                  "expr": {
                                    "name": "Message",
                                    "value": "after restart"
                                  }
                                }
                              }
                            }
                          }
                        }
                      },
                      "body": {
                        "tisyn": "eval",
                        "id": "let",
                        "data": {
                          "tisyn": "quote",
                          "expr": {
                            "name": "__discard_3",
                            "value": {
                              "tisyn": "eval",
                              "id": "dom.click",
                              "data": {
                                "tisyn": "eval",
                                "id": "construct",
                                "data": {
                                  "tisyn": "quote",
                                  "expr": {
                                    "input": {
                                      "tisyn": "eval",
                                      "id": "construct",
                                      "data": {
                                        "tisyn": "quote",
                                        "expr": {
                                          "role": "button",
                                          "name": "Send"
                                        }
                                      }
                                    }
                                  }
                                }
                              }
                            },
                            "body": {
                              "tisyn": "eval",
                              "id": "dom.expectVisible",
                              "data": {
                                "tisyn": "eval",
                                "id": "construct",
                                "data": {
                                  "tisyn": "quote",
                                  "expr": {
                                    "input": {
                                      "tisyn": "eval",
                                      "id": "construct",
                                      "data": {
                                        "tisyn": "quote",
                                        "expr": {
                                          "text": "Assistant: Echo: after restart"
                                        }
                                      }
                                    }
                                  }
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  } as const;

/**
 * Printed Tisyn IR:
 *
 * Fn([],
 *   Let(
 *     "__discard_0",
 *     Eval("dom.expectStatusText",
 *       Construct({
 *         input: Construct({
 *             text: "Session owned by another browser"
 *           })
 *       })),
 *     Let(
 *       "__discard_1",
 *       Eval("dom.expectDisabled",
 *         Construct({
 *           input: Construct({
 *               role: "textbox",
 *               name: "Message"
 *             })
 *         })),
 *       Let(
 *         "__discard_2",
 *         Eval("dom.expectDisabled",
 *           Construct({
 *             input: Construct({
 *                 role: "button",
 *                 name: "Send"
 *               })
 *           })),
 *         Eval("dom.expectTranscript",
 *           Construct({
 *             input: Construct({
 *                 messages: Arr(
 *                     "You: hello",
 *                     "Assistant: Echo: hello"
 *                   )
 *               })
 *           }))
 *       )
 *     )
 *   ))
 */
export const verifySecondBrowserReadOnlyDom: TisynFn<[], unknown> = {
    "tisyn": "fn",
    "params": [],
    "body": {
      "tisyn": "eval",
      "id": "let",
      "data": {
        "tisyn": "quote",
        "expr": {
          "name": "__discard_0",
          "value": {
            "tisyn": "eval",
            "id": "dom.expectStatusText",
            "data": {
              "tisyn": "eval",
              "id": "construct",
              "data": {
                "tisyn": "quote",
                "expr": {
                  "input": {
                    "tisyn": "eval",
                    "id": "construct",
                    "data": {
                      "tisyn": "quote",
                      "expr": {
                        "text": "Session owned by another browser"
                      }
                    }
                  }
                }
              }
            }
          },
          "body": {
            "tisyn": "eval",
            "id": "let",
            "data": {
              "tisyn": "quote",
              "expr": {
                "name": "__discard_1",
                "value": {
                  "tisyn": "eval",
                  "id": "dom.expectDisabled",
                  "data": {
                    "tisyn": "eval",
                    "id": "construct",
                    "data": {
                      "tisyn": "quote",
                      "expr": {
                        "input": {
                          "tisyn": "eval",
                          "id": "construct",
                          "data": {
                            "tisyn": "quote",
                            "expr": {
                              "role": "textbox",
                              "name": "Message"
                            }
                          }
                        }
                      }
                    }
                  }
                },
                "body": {
                  "tisyn": "eval",
                  "id": "let",
                  "data": {
                    "tisyn": "quote",
                    "expr": {
                      "name": "__discard_2",
                      "value": {
                        "tisyn": "eval",
                        "id": "dom.expectDisabled",
                        "data": {
                          "tisyn": "eval",
                          "id": "construct",
                          "data": {
                            "tisyn": "quote",
                            "expr": {
                              "input": {
                                "tisyn": "eval",
                                "id": "construct",
                                "data": {
                                  "tisyn": "quote",
                                  "expr": {
                                    "role": "button",
                                    "name": "Send"
                                  }
                                }
                              }
                            }
                          }
                        }
                      },
                      "body": {
                        "tisyn": "eval",
                        "id": "dom.expectTranscript",
                        "data": {
                          "tisyn": "eval",
                          "id": "construct",
                          "data": {
                            "tisyn": "quote",
                            "expr": {
                              "input": {
                                "tisyn": "eval",
                                "id": "construct",
                                "data": {
                                  "tisyn": "quote",
                                  "expr": {
                                    "messages": {
                                      "tisyn": "eval",
                                      "id": "array",
                                      "data": {
                                        "tisyn": "quote",
                                        "expr": {
                                          "items": [
                                            "You: hello",
                                            "Assistant: Echo: hello"
                                          ]
                                        }
                                      }
                                    }
                                  }
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  } as const;

/**
 * Printed Tisyn IR:
 *
 * Fn([],
 *   Let(
 *     "__discard_0",
 *     Eval("dom.expectTranscript",
 *       Construct({
 *         input: Construct({
 *             messages: Arr(
 *                 "You: hello",
 *                 "Assistant: Echo: hello",
 *                 "You: world",
 *                 "Assistant: Echo: world"
 *               )
 *           })
 *       })),
 *     Eval("dom.expectStatusText",
 *       Construct({
 *         input: Construct({
 *             text: "Say something"
 *           })
 *       }))
 *   ))
 */
export const verifyTranscriptAfterReloadDom: TisynFn<[], unknown> = {
    "tisyn": "fn",
    "params": [],
    "body": {
      "tisyn": "eval",
      "id": "let",
      "data": {
        "tisyn": "quote",
        "expr": {
          "name": "__discard_0",
          "value": {
            "tisyn": "eval",
            "id": "dom.expectTranscript",
            "data": {
              "tisyn": "eval",
              "id": "construct",
              "data": {
                "tisyn": "quote",
                "expr": {
                  "input": {
                    "tisyn": "eval",
                    "id": "construct",
                    "data": {
                      "tisyn": "quote",
                      "expr": {
                        "messages": {
                          "tisyn": "eval",
                          "id": "array",
                          "data": {
                            "tisyn": "quote",
                            "expr": {
                              "items": [
                                "You: hello",
                                "Assistant: Echo: hello",
                                "You: world",
                                "Assistant: Echo: world"
                              ]
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          },
          "body": {
            "tisyn": "eval",
            "id": "dom.expectStatusText",
            "data": {
              "tisyn": "eval",
              "id": "construct",
              "data": {
                "tisyn": "quote",
                "expr": {
                  "input": {
                    "tisyn": "eval",
                    "id": "construct",
                    "data": {
                      "tisyn": "quote",
                      "expr": {
                        "text": "Say something"
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  } as const;

export const agents = { Dom };
export const workflows = { basicSendReceiveDom, expectDisconnectedDom, sendBeforeRestartDom, sendFirstMessageDom, sendTwoMessagesDom, verifyDefaultSessionEnabledDom, verifyRestoredAndSendAfterRestartDom, verifySecondBrowserReadOnlyDom, verifyTranscriptAfterReloadDom };
