// Auto-generated by @tisyn/compiler — do not edit
import { agent, operation } from "@tisyn/agent";
import type { DeclaredAgent, OperationSpec } from "@tisyn/agent";
import type { TisynFn } from "@tisyn/ir";
import { Fn, Eval, Let, Construct, Arr } from "@tisyn/ir";

export function TestBrowser(): DeclaredAgent<{ open: OperationSpec<{ input: Record<string, never> }, void>; reload: OperationSpec<{ input: Record<string, never> }, void>; close: OperationSpec<{ input: Record<string, never> }, void>; openSession: OperationSpec<{ input: { sessionId: string } }, void>; switchSession: OperationSpec<{ input: { sessionId: string } }, void>; closeSession: OperationSpec<{ input: { sessionId: string } }, void>; fill: OperationSpec<{ input: { name: string; value: string } }, void>; click: OperationSpec<{ input: { role: string; name: string } }, void>; pressKey: OperationSpec<{ input: { key: string } }, void>; expectVisible: OperationSpec<{ input: { text: string } }, void>; expectNotVisible: OperationSpec<{ input: { text: string } }, void>; expectDisabled: OperationSpec<{ input: { role: string; name: string } }, void>; expectEnabled: OperationSpec<{ input: { role: string; name: string } }, void>; expectTranscript: OperationSpec<{ input: { messages: string[] } }, void>; expectStatusText: OperationSpec<{ input: { text: string } }, void> }> {
  const id = "test-browser";
  return agent(id, {
    open: operation<{ input: Record<string, never> }, void>(),
    reload: operation<{ input: Record<string, never> }, void>(),
    close: operation<{ input: Record<string, never> }, void>(),
    openSession: operation<{ input: { sessionId: string } }, void>(),
    switchSession: operation<{ input: { sessionId: string } }, void>(),
    closeSession: operation<{ input: { sessionId: string } }, void>(),
    fill: operation<{ input: { name: string; value: string } }, void>(),
    click: operation<{ input: { role: string; name: string } }, void>(),
    pressKey: operation<{ input: { key: string } }, void>(),
    expectVisible: operation<{ input: { text: string } }, void>(),
    expectNotVisible: operation<{ input: { text: string } }, void>(),
    expectDisabled: operation<{ input: { role: string; name: string } }, void>(),
    expectEnabled: operation<{ input: { role: string; name: string } }, void>(),
    expectTranscript: operation<{ input: { messages: string[] } }, void>(),
    expectStatusText: operation<{ input: { text: string } }, void>(),
  });
}

export function TestHost(): DeclaredAgent<{ stop: OperationSpec<{ input: Record<string, never> }, void>; restart: OperationSpec<{ input: { journalPath?: string } }, void> }> {
  const id = "test-host";
  return agent(id, {
    stop: operation<{ input: Record<string, never> }, void>(),
    restart: operation<{ input: { journalPath?: string } }, void>(),
  });
}

export const basicSendReceive: TisynFn<[], unknown> =
  Fn([],
    Let(
      "__discard_0",
      Eval("test-browser.open",
        Construct({
          input: Construct({
  
            })
        })),
      Let(
        "__discard_1",
        Eval("test-browser.expectStatusText",
          Construct({
            input: Construct({
                text: "Say something"
              })
          })),
        Let(
          "__discard_2",
          Eval("test-browser.fill",
            Construct({
              input: Construct({
                  name: "Message",
                  value: "hello"
                })
            })),
          Let(
            "__discard_3",
            Eval("test-browser.click",
              Construct({
                input: Construct({
                    role: "button",
                    name: "Send"
                  })
              })),
            Let(
              "__discard_4",
              Eval("test-browser.expectVisible",
                Construct({
                  input: Construct({
                      text: "Echo: hello"
                    })
                })),
              Eval("test-browser.expectTranscript",
                Construct({
                  input: Construct({
                      messages: Arr(
                          "You: hello",
                          "Assistant: Echo: hello"
                        )
                    })
                }))
            )
          )
        )
      )
    ));

export const hostRestartPreservesState: TisynFn<[], unknown> =
  Fn([],
    Let(
      "__discard_0",
      Eval("test-browser.open",
        Construct({
          input: Construct({
  
            })
        })),
      Let(
        "__discard_1",
        Eval("test-browser.expectStatusText",
          Construct({
            input: Construct({
                text: "Say something"
              })
          })),
        Let(
          "__discard_2",
          Eval("test-browser.fill",
            Construct({
              input: Construct({
                  name: "Message",
                  value: "before restart"
                })
            })),
          Let(
            "__discard_3",
            Eval("test-browser.click",
              Construct({
                input: Construct({
                    role: "button",
                    name: "Send"
                  })
              })),
            Let(
              "__discard_4",
              Eval("test-browser.expectVisible",
                Construct({
                  input: Construct({
                      text: "Echo: before restart"
                    })
                })),
              Let(
                "__discard_5",
                Eval("test-host.restart",
                  Construct({
                    input: Construct({
  
                      })
                  })),
                Let(
                  "__discard_6",
                  Eval("test-browser.expectStatusText",
                    Construct({
                      input: Construct({
                          text: "Disconnected"
                        })
                    })),
                  Let(
                    "__discard_7",
                    Eval("test-browser.reload",
                      Construct({
                        input: Construct({
  
                          })
                      })),
                    Let(
                      "__discard_8",
                      Eval("test-browser.expectTranscript",
                        Construct({
                          input: Construct({
                              messages: Arr(
                                  "You: before restart",
                                  "Assistant: Echo: before restart"
                                )
                            })
                        })),
                      Let(
                        "__discard_9",
                        Eval("test-browser.expectStatusText",
                          Construct({
                            input: Construct({
                                text: "Say something"
                              })
                          })),
                        Let(
                          "__discard_10",
                          Eval("test-browser.fill",
                            Construct({
                              input: Construct({
                                  name: "Message",
                                  value: "after restart"
                                })
                            })),
                          Let(
                            "__discard_11",
                            Eval("test-browser.click",
                              Construct({
                                input: Construct({
                                    role: "button",
                                    name: "Send"
                                  })
                              })),
                            Eval("test-browser.expectVisible",
                              Construct({
                                input: Construct({
                                    text: "Echo: after restart"
                                  })
                              }))
                          )
                        )
                      )
                    )
                  )
                )
              )
            )
          )
        )
      )
    ));

export const secondBrowserIsReadOnly: TisynFn<[], unknown> =
  Fn([],
    Let(
      "__discard_0",
      Eval("test-browser.open",
        Construct({
          input: Construct({
  
            })
        })),
      Let(
        "__discard_1",
        Eval("test-browser.expectStatusText",
          Construct({
            input: Construct({
                text: "Say something"
              })
          })),
        Let(
          "__discard_2",
          Eval("test-browser.fill",
            Construct({
              input: Construct({
                  name: "Message",
                  value: "hello"
                })
            })),
          Let(
            "__discard_3",
            Eval("test-browser.click",
              Construct({
                input: Construct({
                    role: "button",
                    name: "Send"
                  })
              })),
            Let(
              "__discard_4",
              Eval("test-browser.expectVisible",
                Construct({
                  input: Construct({
                      text: "Echo: hello"
                    })
                })),
              Let(
                "__discard_5",
                Eval("test-browser.openSession",
                  Construct({
                    input: Construct({
                        sessionId: "second"
                      })
                  })),
                Let(
                  "__discard_6",
                  Eval("test-browser.expectStatusText",
                    Construct({
                      input: Construct({
                          text: "Session owned by another browser"
                        })
                    })),
                  Let(
                    "__discard_7",
                    Eval("test-browser.expectDisabled",
                      Construct({
                        input: Construct({
                            role: "textbox",
                            name: "Message"
                          })
                      })),
                    Let(
                      "__discard_8",
                      Eval("test-browser.expectDisabled",
                        Construct({
                          input: Construct({
                              role: "button",
                              name: "Send"
                            })
                        })),
                      Let(
                        "__discard_9",
                        Eval("test-browser.expectTranscript",
                          Construct({
                            input: Construct({
                                messages: Arr(
                                    "You: hello",
                                    "Assistant: Echo: hello"
                                  )
                              })
                          })),
                        Let(
                          "__discard_10",
                          Eval("test-browser.switchSession",
                            Construct({
                              input: Construct({
                                  sessionId: "default"
                                })
                            })),
                          Let(
                            "__discard_11",
                            Eval("test-browser.expectEnabled",
                              Construct({
                                input: Construct({
                                    role: "textbox",
                                    name: "Message"
                                  })
                              })),
                            Eval("test-browser.closeSession",
                              Construct({
                                input: Construct({
                                    sessionId: "second"
                                  })
                              }))
                          )
                        )
                      )
                    )
                  )
                )
              )
            )
          )
        )
      )
    ));

export const transcriptRestoresAfterReload: TisynFn<[], unknown> =
  Fn([],
    Let(
      "__discard_0",
      Eval("test-browser.open",
        Construct({
          input: Construct({
  
            })
        })),
      Let(
        "__discard_1",
        Eval("test-browser.expectStatusText",
          Construct({
            input: Construct({
                text: "Say something"
              })
          })),
        Let(
          "__discard_2",
          Eval("test-browser.fill",
            Construct({
              input: Construct({
                  name: "Message",
                  value: "hello"
                })
            })),
          Let(
            "__discard_3",
            Eval("test-browser.click",
              Construct({
                input: Construct({
                    role: "button",
                    name: "Send"
                  })
              })),
            Let(
              "__discard_4",
              Eval("test-browser.expectVisible",
                Construct({
                  input: Construct({
                      text: "Echo: hello"
                    })
                })),
              Let(
                "__discard_5",
                Eval("test-browser.fill",
                  Construct({
                    input: Construct({
                        name: "Message",
                        value: "world"
                      })
                  })),
                Let(
                  "__discard_6",
                  Eval("test-browser.click",
                    Construct({
                      input: Construct({
                          role: "button",
                          name: "Send"
                        })
                    })),
                  Let(
                    "__discard_7",
                    Eval("test-browser.expectVisible",
                      Construct({
                        input: Construct({
                            text: "Echo: world"
                          })
                      })),
                    Let(
                      "__discard_8",
                      Eval("test-browser.reload",
                        Construct({
                          input: Construct({
  
                            })
                        })),
                      Let(
                        "__discard_9",
                        Eval("test-browser.expectTranscript",
                          Construct({
                            input: Construct({
                                messages: Arr(
                                    "You: hello",
                                    "Assistant: Echo: hello",
                                    "You: world",
                                    "Assistant: Echo: world"
                                  )
                              })
                          })),
                        Eval("test-browser.expectStatusText",
                          Construct({
                            input: Construct({
                                text: "Say something"
                              })
                          }))
                      )
                    )
                  )
                )
              )
            )
          )
        )
      )
    ));

export const agents = { TestBrowser, TestHost };
export const workflows = { basicSendReceive, hostRestartPreservesState, secondBrowserIsReadOnly, transcriptRestoresAfterReload };
