/**
 * Generate TypeScript source for a .generated.ts workflow module.
 *
 * Produces factory-shaped agent declarations, compiled workflow IR exports,
 * and grouped agents/workflows maps.
 */

import type { TisynExpr as Expr } from "@tisyn/ir";
import type { DiscoveredContract } from "./discover.js";

/**
 * Generate TypeScript module source from discovered contracts and compiled workflows.
 */
export function generateCode(
  contracts: DiscoveredContract[],
  workflows: Record<string, Expr>,
  typeImports: string[],
): string {
  const lines: string[] = [];

  lines.push("// Auto-generated by @tisyn/compiler — do not edit");
  lines.push('import { agent, operation } from "@tisyn/agent";');

  // Forward referenced type imports from source
  for (const imp of typeImports) {
    lines.push(imp);
  }

  lines.push("");

  // Sort contracts by name for deterministic output
  const sortedContracts = [...contracts].sort((a, b) =>
    a.name.localeCompare(b.name),
  );

  // Generate factory-shaped agent declarations
  for (const contract of sortedContracts) {
    lines.push(generateFactory(contract));
    lines.push("");
  }

  // Generate workflow IR exports
  const sortedWorkflowNames = Object.keys(workflows).sort();
  for (const name of sortedWorkflowNames) {
    const ir = workflows[name]!;
    const json = JSON.stringify(ir, null, 2);
    // Indent the JSON body to align with the export
    const indented = json
      .split("\n")
      .map((line, i) => (i === 0 ? line : `  ${line}`))
      .join("\n");
    lines.push(`export const ${name} = ${indented} as const;`);
    lines.push("");
  }

  // Generate grouped exports
  if (sortedContracts.length > 0) {
    const agentNames = sortedContracts.map((c) => c.name).join(", ");
    lines.push(`export const agents = { ${agentNames} };`);
  }

  if (sortedWorkflowNames.length > 0) {
    const workflowNames = sortedWorkflowNames.join(", ");
    lines.push(`export const workflows = { ${workflowNames} };`);
  }

  lines.push("");

  return lines.join("\n");
}

function generateFactory(contract: DiscoveredContract): string {
  const { name, baseAgentId, hasInstance, methods } = contract;

  const lines: string[] = [];

  if (hasInstance) {
    lines.push(`export function ${name}(instance?: string) {`);
    lines.push(
      `  const id = instance ? \`${baseAgentId}:\${instance}\` : "${baseAgentId}";`,
    );
  } else {
    lines.push(`export function ${name}() {`);
    lines.push(`  const id = "${baseAgentId}";`);
  }

  lines.push(`  return agent(id, {`);

  for (let i = 0; i < methods.length; i++) {
    const method = methods[i]!;
    const payloadFields = method.params
      .map((p) => `${p.name}: ${p.type}`)
      .join("; ");
    const trailing = i < methods.length - 1 ? "," : ",";
    lines.push(
      `    ${method.name}: operation<{ ${payloadFields} }, ${method.resultType}>()${trailing}`,
    );
  }

  lines.push(`  });`);
  lines.push(`}`);

  return lines.join("\n");
}
