/**
 * Generate TypeScript source for a .generated.ts workflow module.
 *
 * Produces factory-shaped agent declarations, compiled workflow IR exports,
 * and grouped agents/workflows maps.
 */

import ts from "typescript";
import type { TisynExpr as Expr } from "@tisyn/ir";
import { print } from "@tisyn/ir";
import type { DiscoveredContract } from "./discover.js";
import type { CompiledSymbol } from "./compile-symbols.js";

export interface WorkflowInfo {
  ir: Expr;
  paramTypes: string[];
  returnType: string;
}

// ── Input Schema Types ──

export interface InputFieldSchema {
  name: string;
  fieldType: "string" | "number" | "boolean";
  optional: boolean;
}

export type InputSchema =
  | { type: "none" }
  | { type: "object"; fields: InputFieldSchema[] }
  | { type: "unsupported"; reason: string };

const PRIMITIVE_TYPE_MAP: Record<string, "string" | "number" | "boolean"> = {
  string: "string",
  number: "number",
  boolean: "boolean",
};

/**
 * Build an InputSchema from the workflow's paramTypes.
 *
 * Supports:
 * - Zero parameters → { type: "none" }
 * - One flat object parameter with primitive fields → { type: "object", fields: [...] }
 * - Anything else → { type: "unsupported", reason: "..." }
 */
export function buildInputSchema(paramTypes: string[]): InputSchema {
  if (paramTypes.length === 0) {
    return { type: "none" };
  }
  if (paramTypes.length > 1) {
    return { type: "unsupported", reason: "multiple parameters" };
  }

  const typeStr = paramTypes[0]!.trim();

  // Parse the type string using the TypeScript compiler API
  const sourceFile = ts.createSourceFile(
    "__schema.ts",
    `type __T = ${typeStr};`,
    ts.ScriptTarget.Latest,
    true,
  );

  const typeAlias = sourceFile.statements[0];
  if (!typeAlias || !ts.isTypeAliasDeclaration(typeAlias) || !typeAlias.type) {
    return { type: "unsupported", reason: `cannot parse type: ${typeStr}` };
  }

  const typeNode = typeAlias.type;

  if (!ts.isTypeLiteralNode(typeNode)) {
    return { type: "unsupported", reason: `parameter type is not an object literal: ${typeStr}` };
  }

  const fields: InputFieldSchema[] = [];
  for (const member of typeNode.members) {
    if (!ts.isPropertySignature(member)) {
      return { type: "unsupported", reason: "object type contains non-property member" };
    }
    if (!member.name || !ts.isIdentifier(member.name)) {
      return { type: "unsupported", reason: "object type contains computed property" };
    }
    const name = member.name.text;
    const optional = !!member.questionToken;

    if (!member.type) {
      return { type: "unsupported", reason: `field '${name}' has no type annotation` };
    }

    const fieldTypeText = member.type.getText(sourceFile);
    const fieldType = PRIMITIVE_TYPE_MAP[fieldTypeText];
    if (!fieldType) {
      return {
        type: "unsupported",
        reason: `field '${name}' has unsupported type '${fieldTypeText}'`,
      };
    }

    fields.push({ name, fieldType, optional });
  }

  return { type: "object", fields };
}

/** All IR constructor names that print() can emit, in deterministic order. */
const ALL_IR_CONSTRUCTORS = [
  "Fn",
  "Q",
  "Ref",
  "Eval",
  "Let",
  "Seq",
  "If",
  "While",
  "Call",
  "Get",
  "Add",
  "Sub",
  "Mul",
  "Div",
  "Mod",
  "Neg",
  "Gt",
  "Gte",
  "Lt",
  "Lte",
  "Eq",
  "Neq",
  "And",
  "Or",
  "Not",
  "Construct",
  "Arr",
  "Concat",
  "ConcatArrays",
  "MergeObjects",
  "Throw",
  "Try",
  "All",
  "Race",
  "Spawn",
  "Join",
  "Resource",
  "Provide",
  "Timebox",
];

/** Scan printed constructor-form sources and return only the constructor names actually used. */
function scanUsedConstructors(printedSources: string[]): string[] {
  const combined = printedSources.join("\n");
  return ALL_IR_CONSTRUCTORS.filter((name) =>
    new RegExp(`\\b${name}(?:<[^>]*>)?\\(`).test(combined),
  );
}

/**
 * Generate TypeScript module source from discovered contracts and compiled workflows.
 */
export function generateCode(
  contracts: DiscoveredContract[],
  workflows: Record<string, WorkflowInfo>,
  typeImports: string[],
  workflowFormat: "printed" | "json" = "printed",
): string {
  const lines: string[] = [];

  const sortedWorkflowNames = Object.keys(workflows).sort();
  const sortedContracts = [...contracts].sort((a, b) => a.name.localeCompare(b.name));

  // Pre-compute printed output so we can scan for used constructors before emitting imports
  const printedMap: Record<string, string> = {};
  if (workflowFormat === "printed") {
    for (const name of sortedWorkflowNames) {
      printedMap[name] = print(workflows[name]!.ir, { compact: false, refTypeAnnotation: "any" });
    }
  }

  lines.push("// Auto-generated by @tisyn/compiler — do not edit");
  lines.push('import { agent, operation } from "@tisyn/agent";');

  // Type imports needed for annotated output
  if (sortedContracts.length > 0) {
    lines.push('import type { DeclaredAgent, OperationSpec } from "@tisyn/agent";');
  }
  if (sortedWorkflowNames.length > 0) {
    lines.push('import type { TisynFn } from "@tisyn/ir";');
    if (workflowFormat === "printed") {
      const usedConstructors = scanUsedConstructors(Object.values(printedMap));
      if (usedConstructors.length > 0) {
        lines.push(`import { ${usedConstructors.join(", ")} } from "@tisyn/ir";`);
      }
    }
  }

  // Forward referenced type imports from source
  for (const imp of typeImports) {
    lines.push(imp);
  }

  lines.push("");

  // Generate factory-shaped agent declarations
  for (const contract of sortedContracts) {
    lines.push(generateFactory(contract));
    lines.push("");
  }

  // Generate workflow IR exports
  for (const name of sortedWorkflowNames) {
    const wf = workflows[name]!;
    const paramTypesList = wf.paramTypes.join(", ");
    const fnType = `TisynFn<[${paramTypesList}], ${wf.returnType}>`;

    if (workflowFormat === "printed") {
      const indented = indentContinuation(printedMap[name]!);
      lines.push(`export const ${name}: ${fnType} =\n  ${indented};`);
    } else {
      const json = sortedStringify(wf.ir, 2);
      const indented = indentContinuation(json);
      lines.push(generateWorkflowDoc(name, wf.ir));
      lines.push(`export const ${name}: ${fnType} = ${indented} as const;`);
    }
    lines.push("");
  }

  // Generate grouped exports
  if (sortedContracts.length > 0) {
    const agentNames = sortedContracts.map((c) => c.name).join(", ");
    lines.push(`export const agents = { ${agentNames} };`);
  }

  if (sortedWorkflowNames.length > 0) {
    const workflowNames = sortedWorkflowNames.join(", ");
    lines.push(`export const workflows = { ${workflowNames} };`);
  }

  // Generate input schema metadata
  if (sortedWorkflowNames.length > 0) {
    lines.push("");
    const schemaEntries: string[] = [];
    for (const name of sortedWorkflowNames) {
      const wf = workflows[name]!;
      const schema = buildInputSchema(wf.paramTypes);
      schemaEntries.push(`  ${name}: ${sortedStringify(schema)}`);
    }
    lines.push(`export const inputSchemas = {`);
    lines.push(schemaEntries.join(",\n"));
    lines.push(`};`);
  }

  lines.push("");

  return lines.join("\n");
}

function generateFactoryReturnType(contract: DiscoveredContract): string {
  const opsEntries = contract.methods.map((method) => {
    const inputFields = method.params.map((p) => `${p.name}: ${p.type}`).join("; ");
    return `${method.name}: OperationSpec<{ ${inputFields} }, ${method.resultType}>`;
  });
  return `DeclaredAgent<{ ${opsEntries.join("; ")} }>`;
}

function generateFactory(contract: DiscoveredContract): string {
  const { name, baseAgentId, hasInstance, methods } = contract;

  const lines: string[] = [];
  const returnType = generateFactoryReturnType(contract);

  if (hasInstance) {
    lines.push(`export function ${name}(instance?: string): ${returnType} {`);
    lines.push(`  const id = instance ? \`${baseAgentId}:\${instance}\` : "${baseAgentId}";`);
  } else {
    lines.push(`export function ${name}(): ${returnType} {`);
    lines.push(`  const id = "${baseAgentId}";`);
  }

  lines.push(`  return agent(id, {`);

  for (let i = 0; i < methods.length; i++) {
    const method = methods[i]!;
    const payloadFields = method.params.map((p) => `${p.name}: ${p.type}`).join("; ");
    const trailing = i < methods.length - 1 ? "," : ",";
    lines.push(
      `    ${method.name}: operation<{ ${payloadFields} }, ${method.resultType}>()${trailing}`,
    );
  }

  lines.push(`  });`);
  lines.push(`}`);

  return lines.join("\n");
}

/**
 * JSON.stringify with sorted keys for deterministic output.
 */
function sortedStringify(value: unknown, indent?: number): string {
  return JSON.stringify(
    value,
    (_key, val) => {
      if (val && typeof val === "object" && !Array.isArray(val)) {
        const sorted: Record<string, unknown> = {};
        for (const k of Object.keys(val).sort()) {
          sorted[k] = (val as Record<string, unknown>)[k];
        }
        return sorted;
      }
      return val;
    },
    indent,
  );
}

function indentContinuation(source: string): string {
  return source
    .split("\n")
    .map((line, i) => (i === 0 ? line : `  ${line}`))
    .join("\n");
}

function generateWorkflowDoc(_name: string, ir: Expr): string {
  const source = print(ir, { compact: false });
  const sourceLines = source.split("\n");
  return [
    "/**",
    " * Printed Tisyn IR:",
    " *",
    ...sourceLines.map((line) => {
      // Escape comment terminators so decompiled strings containing */ don't break the JSDoc
      const safe = line.replace(/\*\//g, "*\\/");
      return safe ? ` * ${safe}` : " *";
    }),
    " */",
  ].join("\n");
}

// ── Graph-mode code generation ──

export interface GenerateGraphCodeOptions {
  symbols: CompiledSymbol[];
  contracts: DiscoveredContract[];
  typeImports: string[];
  generatedImports: { names: string[]; path: string }[];
  format: "printed" | "json";
}

/**
 * Generate TypeScript module source from a compiled import graph.
 *
 * Like generateCode but operates on CompiledSymbol[] with module-scoped
 * emitted names, handles generated-module imports (GM6), and emits
 * all compiled bindings (workflows + helpers) in topological order.
 */
export function generateGraphCode(options: GenerateGraphCodeOptions): string {
  const { symbols, contracts, typeImports, generatedImports, format } = options;

  const lines: string[] = [];

  // Separate exported workflows (generators) from all symbols
  const exportedWorkflows = symbols.filter((s) => s.isExported && s.isGenerator);

  const allSymbols = [...symbols];
  const sortedContracts = [...contracts].sort((a, b) => a.name.localeCompare(b.name));

  // Pre-compute printed output for constructor scanning
  const printedMap = new Map<string, string>();
  if (format === "printed") {
    for (const sym of allSymbols) {
      printedMap.set(sym.emittedName, print(sym.ir, { compact: false, refTypeAnnotation: "any" }));
    }
  }

  lines.push("// Auto-generated by @tisyn/compiler — do not edit");
  lines.push('import { agent, operation } from "@tisyn/agent";');

  if (sortedContracts.length > 0) {
    lines.push('import type { DeclaredAgent, OperationSpec } from "@tisyn/agent";');
  }

  if (allSymbols.length > 0) {
    lines.push('import type { TisynFn } from "@tisyn/ir";');
    if (format === "printed") {
      const usedConstructors = scanUsedConstructors([...printedMap.values()]);
      if (usedConstructors.length > 0) {
        lines.push(`import { ${usedConstructors.join(", ")} } from "@tisyn/ir";`);
      }
    }
  }

  // GM6: Import from generated modules
  for (const imp of generatedImports) {
    const sortedNames = [...imp.names].sort();
    lines.push(`import { ${sortedNames.join(", ")} } from "${imp.path}";`);
  }

  // Forward type imports from across the graph
  for (const imp of typeImports) {
    lines.push(imp);
  }

  lines.push("");

  // Generate factory-shaped agent declarations
  for (const contract of sortedContracts) {
    lines.push(generateFactory(contract));
    lines.push("");
  }

  // Emit all compiled bindings in order (topological/lexicographic — already ordered)
  for (const sym of allSymbols) {
    const exportPrefix = sym.isExported ? "export " : "";
    const paramTypesList = sym.paramTypes.join(", ");
    const fnType = `TisynFn<[${paramTypesList}], ${sym.returnType}>`;

    if (format === "printed") {
      const printed = printedMap.get(sym.emittedName)!;
      const indented = indentContinuation(printed);
      lines.push(`${exportPrefix}const ${sym.emittedName}: ${fnType} =\n  ${indented};`);
    } else {
      const json = sortedStringify(sym.ir, 2);
      const indented = indentContinuation(json);
      if (sym.isExported) {
        lines.push(generateWorkflowDoc(sym.emittedName, sym.ir));
      }
      lines.push(`${exportPrefix}const ${sym.emittedName}: ${fnType} = ${indented} as const;`);
    }
    lines.push("");
  }

  // Grouped exports
  if (sortedContracts.length > 0) {
    const agentNames = sortedContracts.map((c) => c.name).join(", ");
    lines.push(`export const agents = { ${agentNames} };`);
  }

  if (exportedWorkflows.length > 0) {
    const workflowNames = exportedWorkflows.map((s) => s.emittedName).join(", ");
    lines.push(`export const workflows = { ${workflowNames} };`);
  }

  // Input schema metadata for exported workflows
  if (exportedWorkflows.length > 0) {
    lines.push("");
    const schemaEntries: string[] = [];
    for (const sym of exportedWorkflows) {
      schemaEntries.push(`  ${sym.emittedName}: ${sortedStringify(sym.inputSchema)}`);
    }
    lines.push(`export const inputSchemas = {`);
    lines.push(schemaEntries.join(",\n"));
    lines.push(`};`);
  }

  lines.push("");

  return lines.join("\n");
}
