/**
 * Conformance tests for compileGraph — rooted import-graph compilation.
 *
 * Tests observe only the public result surface:
 * - result.source — emitted artifact text
 * - result.graph.modules — module categories and participation
 * - result.graph.compiled — compiled symbol names
 * - result.graph.traversed — traversed module paths
 * - CompileError — error code and diagnostic content
 */

import { describe, it, expect } from "vitest";
import { compileGraph, CompileError } from "./index.js";

function makeReadFile(files: Record<string, string>): (path: string) => string {
  return (path) => {
    if (!(path in files)) { throw new Error(`ENOENT: ${path}`); }
    return files[path]!;
  };
}

// ── Graph construction (§14) ──

describe("module graph construction", () => {
  it("IG-001: single root, no imports", () => {
    const result = compileGraph({
      roots: ["/root.ts"],
      readFile: makeReadFile({
        "/root.ts": `export function* main() { return 1; }`,
      }),
      validate: false,
    });

    expect(result.graph.modules["/root.ts"]?.category).toBe("workflow-implementation");
    expect(result.graph.traversed).toEqual(["/root.ts"]);
    expect(result.graph.compiled).toContain("main");
  });

  it("IG-002: root imports helper", () => {
    const result = compileGraph({
      roots: ["/root.ts"],
      readFile: makeReadFile({
        "/root.ts": `
          import { helper } from "./helper.ts";
          export function* main() { return yield* helper(); }
        `,
        "/helper.ts": `
          export function* helper() { return 42; }
        `,
      }),
      validate: false,
    });

    expect(result.graph.traversed).toContain("/root.ts");
    expect(result.graph.traversed).toContain("/helper.ts");
    expect(result.graph.compiled).toContain("main");
    expect(result.graph.compiled).toContain("helper");
  });

  it("IG-003: import without extension → E-IMPORT-002", () => {
    expect(() =>
      compileGraph({
        roots: ["/root.ts"],
        readFile: makeReadFile({
          "/root.ts": `
            import { helper } from "./helper";
            export function* main() { return yield* helper(); }
          `,
        }),
        validate: false,
      }),
    ).toThrow(CompileError);

    try {
      compileGraph({
        roots: ["/root.ts"],
        readFile: makeReadFile({
          "/root.ts": `import { helper } from "./helper"; export function* main() { return 1; }`,
        }),
        validate: false,
      });
    } catch (e) {
      expect((e as CompileError).code).toBe("E-IMPORT-002");
    }
  });

  it("IG-004: bare specifier import → external boundary, not traversed", () => {
    const result = compileGraph({
      roots: ["/root.ts"],
      readFile: makeReadFile({
        "/root.ts": `
          import { something } from "lodash";
          export function* main() { return 1; }
        `,
      }),
      validate: false,
    });

    expect(result.graph.traversed).toEqual(["/root.ts"]);
  });

  it("IG-005: node: protocol import → external boundary", () => {
    const result = compileGraph({
      roots: ["/root.ts"],
      readFile: makeReadFile({
        "/root.ts": `
          import { readFile } from "node:fs";
          export function* main() { return 1; }
        `,
      }),
      validate: false,
    });

    expect(result.graph.traversed).toEqual(["/root.ts"]);
  });

  it("IG-006: generatedModulePaths → generated classification", () => {
    const result = compileGraph({
      roots: ["/root.ts"],
      readFile: makeReadFile({
        "/root.ts": `
          import { dep } from "./generated.ts";
          export function* main() { return 1; }
        `,
        "/generated.ts": `export const dep = 42;`,
      }),
      generatedModulePaths: ["/generated.ts"],
      validate: false,
    });

    expect(result.graph.modules["/generated.ts"]?.category).toBe("generated");
  });

  it("IG-007: auto-generated banner → generated via heuristic", () => {
    const result = compileGraph({
      roots: ["/root.ts"],
      readFile: makeReadFile({
        "/root.ts": `
          import { dep } from "./prior.ts";
          export function* main() { return 1; }
        `,
        "/prior.ts": `// Auto-generated by @tisyn/compiler — do not edit\nexport const dep = 42;`,
      }),
      validate: false,
    });

    expect(result.graph.modules["/prior.ts"]?.category).toBe("generated");
  });

  it("IG-008: type-only import → not traversed, forwarded", () => {
    const result = compileGraph({
      roots: ["/root.ts"],
      readFile: makeReadFile({
        "/root.ts": `
          import type { MyType } from "./types.ts";
          export function* main() { return 1; }
        `,
      }),
      validate: false,
    });

    // Type-only imports are NOT traversed (no readFile for types.ts)
    expect(result.graph.traversed).toEqual(["/root.ts"]);
    // Type import should be forwarded in artifact
    expect(result.source).toContain("import type");
  });

  it("IG-009: import missing file → E-IMPORT-003", () => {
    expect(() =>
      compileGraph({
        roots: ["/root.ts"],
        readFile: makeReadFile({
          "/root.ts": `
            import { helper } from "./missing.ts";
            export function* main() { return 1; }
          `,
        }),
        validate: false,
      }),
    ).toThrow(CompileError);
  });

  it("IG-010: chain root → A → B → C", () => {
    const result = compileGraph({
      roots: ["/root.ts"],
      readFile: makeReadFile({
        "/root.ts": `
          import { a } from "./a.ts";
          export function* main() { return yield* a(); }
        `,
        "/a.ts": `
          import { b } from "./b.ts";
          export function* a() { return yield* b(); }
        `,
        "/b.ts": `
          import { c } from "./c.ts";
          export function* b() { return yield* c(); }
        `,
        "/c.ts": `
          export function* c() { return 42; }
        `,
      }),
      validate: false,
    });

    expect(result.graph.traversed).toContain("/a.ts");
    expect(result.graph.traversed).toContain("/b.ts");
    expect(result.graph.traversed).toContain("/c.ts");
  });

  it("IG-011: circular import → no error", () => {
    const result = compileGraph({
      roots: ["/root.ts"],
      readFile: makeReadFile({
        "/root.ts": `
          import { a } from "./a.ts";
          export function* main() { return yield* a(); }
        `,
        "/a.ts": `
          import { b } from "./b.ts";
          export function* a() { return yield* b(); }
        `,
        "/b.ts": `
          import { a } from "./a.ts";
          export function* b() { return yield* a(); }
        `,
      }),
      validate: false,
    });

    expect(result.graph.traversed).toContain("/a.ts");
    expect(result.graph.traversed).toContain("/b.ts");
  });
});

// ── Module classification (§15) ──

describe("module classification", () => {
  it("MC-001: module with function* → workflow-implementation", () => {
    const result = compileGraph({
      roots: ["/root.ts"],
      readFile: makeReadFile({
        "/root.ts": `export function* wf() { return 1; }`,
      }),
      validate: false,
    });

    expect(result.graph.modules["/root.ts"]?.category).toBe("workflow-implementation");
  });

  it("MC-002: const-bound generator → workflow-implementation", () => {
    const result = compileGraph({
      roots: ["/root.ts"],
      readFile: makeReadFile({
        "/root.ts": `export const wf = function*() { return 1; };`,
      }),
      validate: false,
    });

    expect(result.graph.modules["/root.ts"]?.category).toBe("workflow-implementation");
  });

  it("MC-009: path in generatedModulePaths → generated", () => {
    const result = compileGraph({
      roots: ["/root.ts"],
      readFile: makeReadFile({
        "/root.ts": `
          import { x } from "./gen.ts";
          export function* wf() { return 1; }
        `,
        "/gen.ts": `export const x = 1;`,
      }),
      generatedModulePaths: ["/gen.ts"],
      validate: false,
    });

    expect(result.graph.modules["/gen.ts"]?.category).toBe("generated");
  });
});

// ── Symbol extraction and reachability (§16) ──

describe("symbol extraction and reachability", () => {
  it("SE-001: exported function* → entrypoint, compiled", () => {
    const result = compileGraph({
      roots: ["/root.ts"],
      readFile: makeReadFile({
        "/root.ts": `export function* process() { return 42; }`,
      }),
      validate: false,
    });

    expect(result.graph.compiled).toContain("process");
  });

  it("SE-002: exported const-bound generator → entrypoint", () => {
    const result = compileGraph({
      roots: ["/root.ts"],
      readFile: makeReadFile({
        "/root.ts": `export const process = function*() { return 42; };`,
      }),
      validate: false,
    });

    expect(result.graph.compiled).toContain("process");
  });

  it("SE-003: non-exported helper called from entrypoint → compiled", () => {
    const result = compileGraph({
      roots: ["/root.ts"],
      readFile: makeReadFile({
        "/root.ts": `
          function* helper() { return 1; }
          export function* main() { return yield* helper(); }
        `,
      }),
      validate: false,
    });

    expect(result.graph.compiled.length).toBe(2);
    // helper should have a module-scoped name
    const helperName = result.graph.compiled.find((n) => n !== "main");
    expect(helperName).toBeDefined();
  });

  it("SE-004: cross-module helper → resolved and compiled", () => {
    const result = compileGraph({
      roots: ["/root.ts"],
      readFile: makeReadFile({
        "/root.ts": `
          import { helper } from "./helpers.ts";
          export function* main() { return yield* helper(); }
        `,
        "/helpers.ts": `
          export function* helper() { return 42; }
        `,
      }),
      validate: false,
    });

    expect(result.graph.compiled).toContain("main");
    expect(result.graph.compiled).toContain("helper");
  });

  it("SE-005: unreachable exported symbol → not compiled", () => {
    const result = compileGraph({
      roots: ["/root.ts"],
      readFile: makeReadFile({
        "/root.ts": `
          export function* main() { return 1; }
          export function* unused() { return 2; }
        `,
      }),
      validate: false,
    });

    // main is the entrypoint, unused is not reachable
    // Both are exported generators so both are entrypoints
    // Actually both are exported generators so both ARE entrypoints
    expect(result.graph.compiled).toContain("main");
    expect(result.graph.compiled).toContain("unused");
  });

  it("SE-006: no generators → E-GRAPH-001", () => {
    expect(() =>
      compileGraph({
        roots: ["/root.ts"],
        readFile: makeReadFile({
          "/root.ts": `export function helper() { return 1; }`,
        }),
        validate: false,
      }),
    ).toThrow(CompileError);

    try {
      compileGraph({
        roots: ["/root.ts"],
        readFile: makeReadFile({
          "/root.ts": `export function helper() { return 1; }`,
        }),
        validate: false,
      });
    } catch (e) {
      expect((e as CompileError).code).toBe("E-GRAPH-001");
    }
  });

  it("SE-007: transitive reachability A → B", () => {
    const result = compileGraph({
      roots: ["/root.ts"],
      readFile: makeReadFile({
        "/root.ts": `
          import { a } from "./a.ts";
          export function* main() { return yield* a(); }
        `,
        "/a.ts": `
          import { b } from "./b.ts";
          export function* a() { return yield* b(); }
        `,
        "/b.ts": `
          export function* b() { return 42; }
        `,
      }),
      validate: false,
    });

    expect(result.graph.compiled).toContain("main");
    expect(result.graph.compiled).toContain("a");
    expect(result.graph.compiled).toContain("b");
  });

  it("SE-009: export { local as exported } → resolves through rename", () => {
    const result = compileGraph({
      roots: ["/root.ts"],
      readFile: makeReadFile({
        "/root.ts": `
          import { exported } from "./mod.ts";
          export function* main() { return yield* exported(); }
        `,
        "/mod.ts": `
          function* local() { return 42; }
          export { local as exported };
        `,
      }),
      validate: false,
    });

    expect(result.graph.compiled).toContain("main");
    expect(result.graph.compiled).toContain("exported");
  });

  it("SE-010: emission order is deterministic", () => {
    const files = {
      "/root.ts": `
        import { a } from "./a.ts";
        import { b } from "./b.ts";
        export function* main() { yield* a(); return yield* b(); }
      `,
      "/a.ts": `export function* a() { return 1; }`,
      "/b.ts": `export function* b() { return 2; }`,
    };

    const r1 = compileGraph({ roots: ["/root.ts"], readFile: makeReadFile(files), validate: false });
    const r2 = compileGraph({ roots: ["/root.ts"], readFile: makeReadFile(files), validate: false });

    expect(r1.graph.compiled).toEqual(r2.graph.compiled);
  });
});

// ── Name conflicts (§19) ──

describe("name conflicts", () => {
  it("NC-001: two modules export same-named generator → E-NAME-001", () => {
    expect(() =>
      compileGraph({
        roots: ["/root.ts"],
        readFile: makeReadFile({
          "/root.ts": `
            import { process } from "./other.ts";
            export function* process() { return yield* process(); }
          `,
          "/other.ts": `
            export function* process() { return 1; }
          `,
        }),
        validate: false,
      }),
    ).toThrow(CompileError);
  });

  it("NC-005: non-exported same-named helpers → distinct names, accepted", () => {
    const result = compileGraph({
      roots: ["/root.ts"],
      readFile: makeReadFile({
        "/root.ts": `
          import { a } from "./a.ts";
          import { b } from "./b.ts";
          function* helper() { return 0; }
          export function* main() { yield* helper(); yield* a(); return yield* b(); }
        `,
        "/a.ts": `
          function* helper() { return 1; }
          export function* a() { return yield* helper(); }
        `,
        "/b.ts": `
          function* helper() { return 2; }
          export function* b() { return yield* helper(); }
        `,
      }),
      validate: false,
    });

    // Should have three distinct names for the three helpers
    const helperNames = result.graph.compiled.filter(
      (n) => n !== "main" && n !== "a" && n !== "b",
    );
    expect(helperNames.length).toBe(3);
    // All distinct (EN2)
    expect(new Set(helperNames).size).toBe(3);
  });
});

// ── Artifact identity and determinism (§22) ──

describe("artifact identity and determinism", () => {
  it("AI-DET-001: same inputs → byte-identical output (printed)", () => {
    const files = {
      "/root.ts": `
        import { helper } from "./h.ts";
        export function* main() { return yield* helper(); }
      `,
      "/h.ts": `export function* helper() { return 42; }`,
    };

    const r1 = compileGraph({ roots: ["/root.ts"], readFile: makeReadFile(files), validate: false });
    const r2 = compileGraph({ roots: ["/root.ts"], readFile: makeReadFile(files), validate: false });

    expect(r1.source).toBe(r2.source);
  });

  it("AI-DET-002: same inputs → byte-identical output (json)", () => {
    const files = {
      "/root.ts": `export function* main() { return 42; }`,
    };

    const r1 = compileGraph({ roots: ["/root.ts"], readFile: makeReadFile(files), validate: false, format: "json" });
    const r2 = compileGraph({ roots: ["/root.ts"], readFile: makeReadFile(files), validate: false, format: "json" });

    expect(r1.source).toBe(r2.source);
  });

  it("AI-CHG-001: modified helper body → different output", () => {
    const base = {
      "/root.ts": `
        import { h } from "./h.ts";
        export function* main() { return yield* h(); }
      `,
    };

    const r1 = compileGraph({
      roots: ["/root.ts"],
      readFile: makeReadFile({ ...base, "/h.ts": `export function* h() { return 1; }` }),
      validate: false,
    });
    const r2 = compileGraph({
      roots: ["/root.ts"],
      readFile: makeReadFile({ ...base, "/h.ts": `export function* h() { return 2; }` }),
      validate: false,
    });

    expect(r1.source).not.toBe(r2.source);
  });

  it("AI-NAME-001: exported symbol uses source name", () => {
    const result = compileGraph({
      roots: ["/root.ts"],
      readFile: makeReadFile({
        "/root.ts": `export function* processOrder() { return 1; }`,
      }),
      validate: false,
    });

    expect(result.graph.compiled).toContain("processOrder");
    expect(result.source).toContain("processOrder");
  });

  it("AI-NAME-002: non-exported same-named helpers → distinct emitted names", () => {
    const result = compileGraph({
      roots: ["/root.ts"],
      readFile: makeReadFile({
        "/root.ts": `
          import { a } from "./a.ts";
          import { b } from "./b.ts";
          export function* main() { yield* a(); return yield* b(); }
        `,
        "/a.ts": `
          function* helper() { return 1; }
          export function* a() { return yield* helper(); }
        `,
        "/b.ts": `
          function* helper() { return 2; }
          export function* b() { return yield* helper(); }
        `,
      }),
      validate: false,
    });

    const helperNames = result.graph.compiled.filter(
      (n) => n !== "main" && n !== "a" && n !== "b",
    );
    expect(helperNames.length).toBe(2);
    expect(helperNames[0]).not.toBe(helperNames[1]);
  });

  it("AI-NAME-003: recompile → identical non-exported names (EN4)", () => {
    const files = {
      "/root.ts": `
        import { a } from "./a.ts";
        function* localHelper() { return 0; }
        export function* main() { yield* localHelper(); return yield* a(); }
      `,
      "/a.ts": `
        function* helper() { return 1; }
        export function* a() { return yield* helper(); }
      `,
    };

    const r1 = compileGraph({ roots: ["/root.ts"], readFile: makeReadFile(files), validate: false });
    const r2 = compileGraph({ roots: ["/root.ts"], readFile: makeReadFile(files), validate: false });

    expect(r1.graph.compiled).toEqual(r2.graph.compiled);
  });

  it("AI-FMT-001: printed vs json → different text, each deterministic", () => {
    const files = {
      "/root.ts": `export function* main() { return 42; }`,
    };

    const printed = compileGraph({ roots: ["/root.ts"], readFile: makeReadFile(files), validate: false, format: "printed" });
    const json = compileGraph({ roots: ["/root.ts"], readFile: makeReadFile(files), validate: false, format: "json" });

    expect(printed.source).not.toBe(json.source);
    // Each is internally deterministic
    const p2 = compileGraph({ roots: ["/root.ts"], readFile: makeReadFile(files), validate: false, format: "printed" });
    const j2 = compileGraph({ roots: ["/root.ts"], readFile: makeReadFile(files), validate: false, format: "json" });
    expect(printed.source).toBe(p2.source);
    expect(json.source).toBe(j2.source);
  });
});

// ── Import semantics ──

describe("import semantics", () => {
  it("rejects dynamic imports (E-IMPORT-006)", () => {
    expect(() =>
      compileGraph({
        roots: ["/root.ts"],
        readFile: makeReadFile({
          "/root.ts": `
            const mod = import("./other.ts");
            export function* main() { return 1; }
          `,
        }),
        validate: false,
      }),
    ).toThrow(CompileError);
  });

  it("rejects value re-exports (E-IMPORT-007)", () => {
    expect(() =>
      compileGraph({
        roots: ["/root.ts"],
        readFile: makeReadFile({
          "/root.ts": `
            export { helper } from "./other.ts";
            export function* main() { return 1; }
          `,
          "/other.ts": `export function* helper() { return 1; }`,
        }),
        validate: false,
      }),
    ).toThrow(CompileError);
  });

  it("rejects default imports (E-IMPORT-007)", () => {
    expect(() =>
      compileGraph({
        roots: ["/root.ts"],
        readFile: makeReadFile({
          "/root.ts": `
            import helper from "./other.ts";
            export function* main() { return 1; }
          `,
        }),
        validate: false,
      }),
    ).toThrow(CompileError);
  });

  it("rejects namespace imports (E-IMPORT-007)", () => {
    expect(() =>
      compileGraph({
        roots: ["/root.ts"],
        readFile: makeReadFile({
          "/root.ts": `
            import * as helpers from "./other.ts";
            export function* main() { return 1; }
          `,
        }),
        validate: false,
      }),
    ).toThrow(CompileError);
  });
});

// ── Participation profiles (§15.7) ──

describe("participation profiles", () => {
  it("workflow-implementation with only generators → implementation", () => {
    const result = compileGraph({
      roots: ["/root.ts"],
      readFile: makeReadFile({
        "/root.ts": `export function* main() { return 1; }`,
      }),
      validate: false,
    });

    expect(result.graph.modules["/root.ts"]?.participation).toEqual(["implementation"]);
  });

  it("generated/type-only/external → no participation", () => {
    const result = compileGraph({
      roots: ["/root.ts"],
      readFile: makeReadFile({
        "/root.ts": `
          import { x } from "./gen.ts";
          export function* main() { return 1; }
        `,
        "/gen.ts": `// Auto-generated by @tisyn/compiler\nexport const x = 1;`,
      }),
      validate: false,
    });

    expect(result.graph.modules["/gen.ts"]?.participation).toBeUndefined();
  });
});

// ── Artifact structure ──

describe("artifact structure", () => {
  it("emitted source contains banner", () => {
    const result = compileGraph({
      roots: ["/root.ts"],
      readFile: makeReadFile({
        "/root.ts": `export function* main() { return 42; }`,
      }),
      validate: false,
    });

    expect(result.source).toContain("Auto-generated by @tisyn/compiler");
  });

  it("emitted source contains workflow export", () => {
    const result = compileGraph({
      roots: ["/root.ts"],
      readFile: makeReadFile({
        "/root.ts": `export function* main() { return 42; }`,
      }),
      validate: false,
    });

    expect(result.source).toContain("export const main");
  });

  it("emitted source contains inputSchemas", () => {
    const result = compileGraph({
      roots: ["/root.ts"],
      readFile: makeReadFile({
        "/root.ts": `export function* main() { return 42; }`,
      }),
      validate: false,
    });

    expect(result.source).toContain("inputSchemas");
  });
});
