/**
 * Conformance tests for compileGraph — rooted import-graph compilation.
 *
 * Tests observe only the public result surface:
 * - result.source — emitted artifact text
 * - result.graph.modules — module categories and participation
 * - result.graph.compiled — compiled symbol names
 * - result.graph.traversed — traversed module paths
 * - CompileError — error code and diagnostic content
 */

import { describe, it, expect } from "vitest";
import { compileGraph, compileGraphForRuntime, CompileError } from "./index.js";
import { collectRefs } from "@tisyn/ir";

function makeReadFile(files: Record<string, string>): (path: string) => string {
  return (path) => {
    if (!(path in files)) {
      throw new Error(`ENOENT: ${path}`);
    }
    return files[path]!;
  };
}

// ── Graph construction (§14) ──

describe("module graph construction", () => {
  it("IG-001: single root, no imports", () => {
    const result = compileGraph({
      roots: ["/root.ts"],
      readFile: makeReadFile({
        "/root.ts": `export function* main() { return 1; }`,
      }),
      validate: false,
    });

    expect(result.graph.modules["/root.ts"]?.category).toBe("workflow-implementation");
    expect(result.graph.traversed).toEqual(["/root.ts"]);
    expect(result.graph.compiled).toContain("main");
  });

  it("IG-002: root imports helper", () => {
    const result = compileGraph({
      roots: ["/root.ts"],
      readFile: makeReadFile({
        "/root.ts": `
          import { helper } from "./helper.ts";
          export function* main() { return yield* helper(); }
        `,
        "/helper.ts": `
          export function* helper() { return 42; }
        `,
      }),
      validate: false,
    });

    expect(result.graph.traversed).toContain("/root.ts");
    expect(result.graph.traversed).toContain("/helper.ts");
    expect(result.graph.compiled).toContain("main");
    expect(result.graph.compiled).toContain("helper");
  });

  it("IG-003: import without extension → E-IMPORT-002", () => {
    expect(() =>
      compileGraph({
        roots: ["/root.ts"],
        readFile: makeReadFile({
          "/root.ts": `
            import { helper } from "./helper";
            export function* main() { return yield* helper(); }
          `,
        }),
        validate: false,
      }),
    ).toThrow(CompileError);

    try {
      compileGraph({
        roots: ["/root.ts"],
        readFile: makeReadFile({
          "/root.ts": `import { helper } from "./helper"; export function* main() { return 1; }`,
        }),
        validate: false,
      });
    } catch (e) {
      expect((e as CompileError).code).toBe("E-IMPORT-002");
    }
  });

  it("IG-004: bare specifier import → external boundary, recorded in graph", () => {
    const result = compileGraph({
      roots: ["/root.ts"],
      readFile: makeReadFile({
        "/root.ts": `
          import { something } from "lodash";
          export function* main() { return 1; }
        `,
      }),
      validate: false,
    });

    // Bare specifier recorded as external boundary (no readFile call for it)
    expect(result.graph.modules["lodash"]?.category).toBe("external");
    expect(result.graph.modules["/root.ts"]?.category).toBe("workflow-implementation");
  });

  it("IG-005: node: protocol import → external boundary, recorded in graph", () => {
    const result = compileGraph({
      roots: ["/root.ts"],
      readFile: makeReadFile({
        "/root.ts": `
          import { readFile } from "node:fs";
          export function* main() { return 1; }
        `,
      }),
      validate: false,
    });

    // node: protocol recorded as external boundary
    expect(result.graph.modules["node:fs"]?.category).toBe("external");
  });

  it("IG-006: generatedModulePaths → generated classification", () => {
    const result = compileGraph({
      roots: ["/root.ts"],
      readFile: makeReadFile({
        "/root.ts": `
          import { dep } from "./generated.ts";
          export function* main() { return 1; }
        `,
        "/generated.ts": `export const dep = 42;`,
      }),
      generatedModulePaths: ["/generated.ts"],
      validate: false,
    });

    expect(result.graph.modules["/generated.ts"]?.category).toBe("generated");
  });

  it("IG-007: auto-generated banner → generated via heuristic", () => {
    const result = compileGraph({
      roots: ["/root.ts"],
      readFile: makeReadFile({
        "/root.ts": `
          import { dep } from "./prior.ts";
          export function* main() { return 1; }
        `,
        "/prior.ts": `// Auto-generated by @tisyn/compiler — do not edit\nexport const dep = 42;`,
      }),
      validate: false,
    });

    expect(result.graph.modules["/prior.ts"]?.category).toBe("generated");
  });

  it("IG-008: type-only import → recorded as type-only, forwarded", () => {
    const result = compileGraph({
      roots: ["/root.ts"],
      readFile: makeReadFile({
        "/root.ts": `
          import type { MyType } from "./types.ts";
          export function* main() { return 1; }
        `,
      }),
      validate: false,
    });

    // Type-only module recorded in graph with category "type-only" (no readFile for types.ts)
    expect(result.graph.modules["/types.ts"]?.category).toBe("type-only");
    // Type import should be forwarded in artifact
    expect(result.source).toContain("import type");
  });

  it("IG-009: import missing file → E-IMPORT-003", () => {
    expect(() =>
      compileGraph({
        roots: ["/root.ts"],
        readFile: makeReadFile({
          "/root.ts": `
            import { helper } from "./missing.ts";
            export function* main() { return 1; }
          `,
        }),
        validate: false,
      }),
    ).toThrow(CompileError);
  });

  it("IG-010: chain root → A → B → C", () => {
    const result = compileGraph({
      roots: ["/root.ts"],
      readFile: makeReadFile({
        "/root.ts": `
          import { a } from "./a.ts";
          export function* main() { return yield* a(); }
        `,
        "/a.ts": `
          import { b } from "./b.ts";
          export function* a() { return yield* b(); }
        `,
        "/b.ts": `
          import { c } from "./c.ts";
          export function* b() { return yield* c(); }
        `,
        "/c.ts": `
          export function* c() { return 42; }
        `,
      }),
      validate: false,
    });

    expect(result.graph.traversed).toContain("/a.ts");
    expect(result.graph.traversed).toContain("/b.ts");
    expect(result.graph.traversed).toContain("/c.ts");
  });

  it("IG-011: circular import → no error", () => {
    const result = compileGraph({
      roots: ["/root.ts"],
      readFile: makeReadFile({
        "/root.ts": `
          import { a } from "./a.ts";
          export function* main() { return yield* a(); }
        `,
        "/a.ts": `
          import { b } from "./b.ts";
          export function* a() { return yield* b(); }
        `,
        "/b.ts": `
          import { a } from "./a.ts";
          export function* b() { return yield* a(); }
        `,
      }),
      validate: false,
    });

    expect(result.graph.traversed).toContain("/a.ts");
    expect(result.graph.traversed).toContain("/b.ts");
  });
});

// ── Module classification (§15) ──

describe("module classification", () => {
  it("MC-001: module with function* → workflow-implementation", () => {
    const result = compileGraph({
      roots: ["/root.ts"],
      readFile: makeReadFile({
        "/root.ts": `export function* wf() { return 1; }`,
      }),
      validate: false,
    });

    expect(result.graph.modules["/root.ts"]?.category).toBe("workflow-implementation");
  });

  it("MC-002: const-bound generator → workflow-implementation", () => {
    const result = compileGraph({
      roots: ["/root.ts"],
      readFile: makeReadFile({
        "/root.ts": `export const wf = function*() { return 1; };`,
      }),
      validate: false,
    });

    expect(result.graph.modules["/root.ts"]?.category).toBe("workflow-implementation");
  });

  it("MC-009: path in generatedModulePaths → generated", () => {
    const result = compileGraph({
      roots: ["/root.ts"],
      readFile: makeReadFile({
        "/root.ts": `
          import { x } from "./gen.ts";
          export function* wf() { return 1; }
        `,
        "/gen.ts": `export const x = 1;`,
      }),
      generatedModulePaths: ["/gen.ts"],
      validate: false,
    });

    expect(result.graph.modules["/gen.ts"]?.category).toBe("generated");
  });
});

// ── Symbol extraction and reachability (§16) ──

describe("symbol extraction and reachability", () => {
  it("SE-001: exported function* → entrypoint, compiled", () => {
    const result = compileGraph({
      roots: ["/root.ts"],
      readFile: makeReadFile({
        "/root.ts": `export function* process() { return 42; }`,
      }),
      validate: false,
    });

    expect(result.graph.compiled).toContain("process");
  });

  it("SE-002: exported const-bound generator → entrypoint", () => {
    const result = compileGraph({
      roots: ["/root.ts"],
      readFile: makeReadFile({
        "/root.ts": `export const process = function*() { return 42; };`,
      }),
      validate: false,
    });

    expect(result.graph.compiled).toContain("process");
  });

  it("SE-003: non-exported helper called from entrypoint → compiled", () => {
    const result = compileGraph({
      roots: ["/root.ts"],
      readFile: makeReadFile({
        "/root.ts": `
          function* helper() { return 1; }
          export function* main() { return yield* helper(); }
        `,
      }),
      validate: false,
    });

    expect(result.graph.compiled.length).toBe(2);
    // helper should have a module-scoped name
    const helperName = result.graph.compiled.find((n) => n !== "main");
    expect(helperName).toBeDefined();
  });

  it("SE-004: cross-module helper → resolved and compiled", () => {
    const result = compileGraph({
      roots: ["/root.ts"],
      readFile: makeReadFile({
        "/root.ts": `
          import { helper } from "./helpers.ts";
          export function* main() { return yield* helper(); }
        `,
        "/helpers.ts": `
          export function* helper() { return 42; }
        `,
      }),
      validate: false,
    });

    expect(result.graph.compiled).toContain("main");
    expect(result.graph.compiled).toContain("helper");
  });

  it("SE-005: unreachable exported symbol → not compiled", () => {
    const result = compileGraph({
      roots: ["/root.ts"],
      readFile: makeReadFile({
        "/root.ts": `
          export function* main() { return 1; }
          export function* unused() { return 2; }
        `,
      }),
      validate: false,
    });

    // main is the entrypoint, unused is not reachable
    // Both are exported generators so both are entrypoints
    // Actually both are exported generators so both ARE entrypoints
    expect(result.graph.compiled).toContain("main");
    expect(result.graph.compiled).toContain("unused");
  });

  it("SE-006: no generators → E-GRAPH-001", () => {
    expect(() =>
      compileGraph({
        roots: ["/root.ts"],
        readFile: makeReadFile({
          "/root.ts": `export function helper() { return 1; }`,
        }),
        validate: false,
      }),
    ).toThrow(CompileError);

    try {
      compileGraph({
        roots: ["/root.ts"],
        readFile: makeReadFile({
          "/root.ts": `export function helper() { return 1; }`,
        }),
        validate: false,
      });
    } catch (e) {
      expect((e as CompileError).code).toBe("E-GRAPH-001");
    }
  });

  it("SE-007: transitive reachability A → B", () => {
    const result = compileGraph({
      roots: ["/root.ts"],
      readFile: makeReadFile({
        "/root.ts": `
          import { a } from "./a.ts";
          export function* main() { return yield* a(); }
        `,
        "/a.ts": `
          import { b } from "./b.ts";
          export function* a() { return yield* b(); }
        `,
        "/b.ts": `
          export function* b() { return 42; }
        `,
      }),
      validate: false,
    });

    expect(result.graph.compiled).toContain("main");
    expect(result.graph.compiled).toContain("a");
    expect(result.graph.compiled).toContain("b");
  });

  it("SE-009: export { local as exported } → resolves through rename", () => {
    const result = compileGraph({
      roots: ["/root.ts"],
      readFile: makeReadFile({
        "/root.ts": `
          import { exported } from "./mod.ts";
          export function* main() { return yield* exported(); }
        `,
        "/mod.ts": `
          function* local() { return 42; }
          export { local as exported };
        `,
      }),
      validate: false,
    });

    expect(result.graph.compiled).toContain("main");
    expect(result.graph.compiled).toContain("exported");
  });

  it("SE-010: emission order is deterministic", () => {
    const files = {
      "/root.ts": `
        import { a } from "./a.ts";
        import { b } from "./b.ts";
        export function* main() { yield* a(); return yield* b(); }
      `,
      "/a.ts": `export function* a() { return 1; }`,
      "/b.ts": `export function* b() { return 2; }`,
    };

    const r1 = compileGraph({
      roots: ["/root.ts"],
      readFile: makeReadFile(files),
      validate: false,
    });
    const r2 = compileGraph({
      roots: ["/root.ts"],
      readFile: makeReadFile(files),
      validate: false,
    });

    expect(r1.graph.compiled).toEqual(r2.graph.compiled);
  });
});

// ── Name conflicts (§19) ──

describe("name conflicts", () => {
  it("NC-001: two modules export same-named generator → E-NAME-001", () => {
    expect(() =>
      compileGraph({
        roots: ["/root.ts"],
        readFile: makeReadFile({
          "/root.ts": `
            import { process } from "./other.ts";
            export function* process() { return yield* process(); }
          `,
          "/other.ts": `
            export function* process() { return 1; }
          `,
        }),
        validate: false,
      }),
    ).toThrow(CompileError);
  });

  it("NC-005: non-exported same-named helpers → distinct names, accepted", () => {
    const result = compileGraph({
      roots: ["/root.ts"],
      readFile: makeReadFile({
        "/root.ts": `
          import { a } from "./a.ts";
          import { b } from "./b.ts";
          function* helper() { return 0; }
          export function* main() { yield* helper(); yield* a(); return yield* b(); }
        `,
        "/a.ts": `
          function* helper() { return 1; }
          export function* a() { return yield* helper(); }
        `,
        "/b.ts": `
          function* helper() { return 2; }
          export function* b() { return yield* helper(); }
        `,
      }),
      validate: false,
    });

    // Should have three distinct names for the three helpers
    const helperNames = result.graph.compiled.filter((n) => n !== "main" && n !== "a" && n !== "b");
    expect(helperNames.length).toBe(3);
    // All distinct (EN2)
    expect(new Set(helperNames).size).toBe(3);
  });
});

// ── Artifact identity and determinism (§22) ──

describe("artifact identity and determinism", () => {
  it("AI-DET-001: same inputs → byte-identical output (printed)", () => {
    const files = {
      "/root.ts": `
        import { helper } from "./h.ts";
        export function* main() { return yield* helper(); }
      `,
      "/h.ts": `export function* helper() { return 42; }`,
    };

    const r1 = compileGraph({
      roots: ["/root.ts"],
      readFile: makeReadFile(files),
      validate: false,
    });
    const r2 = compileGraph({
      roots: ["/root.ts"],
      readFile: makeReadFile(files),
      validate: false,
    });

    expect(r1.source).toBe(r2.source);
  });

  it("AI-DET-002: same inputs → byte-identical output (json)", () => {
    const files = {
      "/root.ts": `export function* main() { return 42; }`,
    };

    const r1 = compileGraph({
      roots: ["/root.ts"],
      readFile: makeReadFile(files),
      validate: false,
      format: "json",
    });
    const r2 = compileGraph({
      roots: ["/root.ts"],
      readFile: makeReadFile(files),
      validate: false,
      format: "json",
    });

    expect(r1.source).toBe(r2.source);
  });

  it("AI-CHG-001: modified helper body → different output", () => {
    const base = {
      "/root.ts": `
        import { h } from "./h.ts";
        export function* main() { return yield* h(); }
      `,
    };

    const r1 = compileGraph({
      roots: ["/root.ts"],
      readFile: makeReadFile({ ...base, "/h.ts": `export function* h() { return 1; }` }),
      validate: false,
    });
    const r2 = compileGraph({
      roots: ["/root.ts"],
      readFile: makeReadFile({ ...base, "/h.ts": `export function* h() { return 2; }` }),
      validate: false,
    });

    expect(r1.source).not.toBe(r2.source);
  });

  it("AI-NAME-001: exported symbol uses source name", () => {
    const result = compileGraph({
      roots: ["/root.ts"],
      readFile: makeReadFile({
        "/root.ts": `export function* processOrder() { return 1; }`,
      }),
      validate: false,
    });

    expect(result.graph.compiled).toContain("processOrder");
    expect(result.source).toContain("processOrder");
  });

  it("AI-NAME-002: non-exported same-named helpers → distinct emitted names", () => {
    const result = compileGraph({
      roots: ["/root.ts"],
      readFile: makeReadFile({
        "/root.ts": `
          import { a } from "./a.ts";
          import { b } from "./b.ts";
          export function* main() { yield* a(); return yield* b(); }
        `,
        "/a.ts": `
          function* helper() { return 1; }
          export function* a() { return yield* helper(); }
        `,
        "/b.ts": `
          function* helper() { return 2; }
          export function* b() { return yield* helper(); }
        `,
      }),
      validate: false,
    });

    const helperNames = result.graph.compiled.filter((n) => n !== "main" && n !== "a" && n !== "b");
    expect(helperNames.length).toBe(2);
    expect(helperNames[0]).not.toBe(helperNames[1]);
  });

  it("AI-NAME-003: recompile → identical non-exported names (EN4)", () => {
    const files = {
      "/root.ts": `
        import { a } from "./a.ts";
        function* localHelper() { return 0; }
        export function* main() { yield* localHelper(); return yield* a(); }
      `,
      "/a.ts": `
        function* helper() { return 1; }
        export function* a() { return yield* helper(); }
      `,
    };

    const r1 = compileGraph({
      roots: ["/root.ts"],
      readFile: makeReadFile(files),
      validate: false,
    });
    const r2 = compileGraph({
      roots: ["/root.ts"],
      readFile: makeReadFile(files),
      validate: false,
    });

    expect(r1.graph.compiled).toEqual(r2.graph.compiled);
  });

  it("AI-FMT-001: printed vs json → different text, each deterministic", () => {
    const files = {
      "/root.ts": `export function* main() { return 42; }`,
    };

    const printed = compileGraph({
      roots: ["/root.ts"],
      readFile: makeReadFile(files),
      validate: false,
      format: "printed",
    });
    const json = compileGraph({
      roots: ["/root.ts"],
      readFile: makeReadFile(files),
      validate: false,
      format: "json",
    });

    expect(printed.source).not.toBe(json.source);
    // Each is internally deterministic
    const p2 = compileGraph({
      roots: ["/root.ts"],
      readFile: makeReadFile(files),
      validate: false,
      format: "printed",
    });
    const j2 = compileGraph({
      roots: ["/root.ts"],
      readFile: makeReadFile(files),
      validate: false,
      format: "json",
    });
    expect(printed.source).toBe(p2.source);
    expect(json.source).toBe(j2.source);
  });
});

// ── Import semantics ──

describe("import semantics", () => {
  it("rejects dynamic imports (E-IMPORT-006)", () => {
    expect(() =>
      compileGraph({
        roots: ["/root.ts"],
        readFile: makeReadFile({
          "/root.ts": `
            const mod = import("./other.ts");
            export function* main() { return 1; }
          `,
        }),
        validate: false,
      }),
    ).toThrow(CompileError);
  });

  it("rejects value re-exports (E-IMPORT-007)", () => {
    expect(() =>
      compileGraph({
        roots: ["/root.ts"],
        readFile: makeReadFile({
          "/root.ts": `
            export { helper } from "./other.ts";
            export function* main() { return 1; }
          `,
          "/other.ts": `export function* helper() { return 1; }`,
        }),
        validate: false,
      }),
    ).toThrow(CompileError);
  });

  it("rejects default imports (E-IMPORT-007)", () => {
    expect(() =>
      compileGraph({
        roots: ["/root.ts"],
        readFile: makeReadFile({
          "/root.ts": `
            import helper from "./other.ts";
            export function* main() { return 1; }
          `,
        }),
        validate: false,
      }),
    ).toThrow(CompileError);
  });

  it("rejects namespace imports (E-IMPORT-007)", () => {
    expect(() =>
      compileGraph({
        roots: ["/root.ts"],
        readFile: makeReadFile({
          "/root.ts": `
            import * as helpers from "./other.ts";
            export function* main() { return 1; }
          `,
        }),
        validate: false,
      }),
    ).toThrow(CompileError);
  });
});

// ── Participation profiles (§15.7) ──

describe("participation profiles", () => {
  it("workflow-implementation with only generators → implementation", () => {
    const result = compileGraph({
      roots: ["/root.ts"],
      readFile: makeReadFile({
        "/root.ts": `export function* main() { return 1; }`,
      }),
      validate: false,
    });

    expect(result.graph.modules["/root.ts"]?.participation).toEqual(["implementation"]);
  });

  it("generated/type-only/external → no participation", () => {
    const result = compileGraph({
      roots: ["/root.ts"],
      readFile: makeReadFile({
        "/root.ts": `
          import { x } from "./gen.ts";
          export function* main() { return 1; }
        `,
        "/gen.ts": `// Auto-generated by @tisyn/compiler\nexport const x = 1;`,
      }),
      validate: false,
    });

    expect(result.graph.modules["/gen.ts"]?.participation).toBeUndefined();
  });
});

// ── Artifact structure ──

describe("artifact structure", () => {
  it("emitted source contains banner", () => {
    const result = compileGraph({
      roots: ["/root.ts"],
      readFile: makeReadFile({
        "/root.ts": `export function* main() { return 42; }`,
      }),
      validate: false,
    });

    expect(result.source).toContain("Auto-generated by @tisyn/compiler");
  });

  it("emitted source contains workflow export", () => {
    const result = compileGraph({
      roots: ["/root.ts"],
      readFile: makeReadFile({
        "/root.ts": `export function* main() { return 42; }`,
      }),
      validate: false,
    });

    expect(result.source).toContain("export const main");
  });

  it("emitted source contains inputSchemas", () => {
    const result = compileGraph({
      roots: ["/root.ts"],
      readFile: makeReadFile({
        "/root.ts": `export function* main() { return 42; }`,
      }),
      validate: false,
    });

    expect(result.source).toContain("inputSchemas");
  });

  it("generated-module import includes only referenced names, not bookkeeping exports", () => {
    const result = compileGraph({
      roots: ["/src/root.ts"],
      readFile: makeReadFile({
        "/src/root.ts": `
          import { MyAgent } from "./prior.generated.ts";
          export function* main() { return 1; }
        `,
        "/src/prior.generated.ts": [
          "// Auto-generated by @tisyn/compiler — do not edit",
          "export function MyAgent() { return {}; }",
          "export const workflows = { someOldWorkflow: {} };",
          "export const inputSchemas = {};",
          "export const agents = { MyAgent };",
        ].join("\n"),
      }),
      outputPath: "/src/output.generated.ts",
      validate: false,
    });

    // Should import only MyAgent via a relative specifier
    const importLine = result.source.split("\n").find((l) => l.includes("prior.generated.ts"));
    expect(importLine).toBe('import { MyAgent } from "./prior.generated.ts";');
  });
});

// ── Public result shape (§13.1) ──

describe("CompileGraphResult normative shape", () => {
  it("includes contracts, workflows, helpers, and warnings", () => {
    const result = compileGraph({
      roots: ["/root.ts"],
      readFile: makeReadFile({
        "/root.ts": `
          declare function Svc(): {
            fetch(id: string): Workflow<string>;
          };
          export function* main(id: string) {
            return yield* Svc().fetch(id);
          }
        `,
      }),
      validate: false,
    });

    expect(result.contracts).toBeInstanceOf(Array);
    expect(result.contracts.length).toBe(1);
    expect(result.contracts[0]!.name).toBe("Svc");

    expect(result.workflows).toBeDefined();
    expect(result.workflows["main"]).toBeDefined();

    expect(result.helpers).toBeDefined();

    expect(result.warnings).toBeInstanceOf(Array);
  });

  it("populates helpers for non-exported compiled symbols", () => {
    const result = compileGraph({
      roots: ["/root.ts"],
      readFile: makeReadFile({
        "/root.ts": `
          import { helper } from "./helper.ts";
          export function* main() { return yield* helper(); }
        `,
        "/helper.ts": `
          export function* helper() { return 42; }
        `,
      }),
      validate: false,
    });

    // helper is exported from helper.ts and reachable, so it appears in compiled
    expect(result.graph.compiled).toContain("helper");
  });

  it("determinism: identical results across repeated runs", () => {
    const files = {
      "/root.ts": `
        import { helper } from "./helper.ts";
        export function* main() { return yield* helper(); }
      `,
      "/helper.ts": `
        export function* helper() { return 42; }
      `,
    };
    const opts = { roots: ["/root.ts"], readFile: makeReadFile(files), validate: false };
    const r1 = compileGraph(opts);
    const r2 = compileGraph(opts);
    expect(r1.source).toBe(r2.source);
    expect(JSON.stringify(r1.graph)).toBe(JSON.stringify(r2.graph));
  });
});

// ── Import boundary diagnostics (§24) ──

describe("import boundary diagnostics", () => {
  it("E-IMPORT-001: rejects value import from bare specifier in reachable code", () => {
    expect(() =>
      compileGraph({
        roots: ["/root.ts"],
        readFile: makeReadFile({
          "/root.ts": `
            import { readFile } from "node:fs";
            export function* main() { return readFile("x"); }
          `,
        }),
        validate: false,
      }),
    ).toThrow(/E-IMPORT-001/);
  });

  it("E-IMPORT-004: rejects reference to traversed module with no workflow symbols", () => {
    expect(() =>
      compileGraph({
        roots: ["/root.ts"],
        readFile: makeReadFile({
          "/root.ts": `
            import { config } from "./config.ts";
            export function* main() { return config(); }
          `,
          "/config.ts": `
            export const config = { key: "value" };
          `,
        }),
        validate: false,
      }),
    ).toThrow(/E-IMPORT-004/);
  });

  it("E-IMPORT-005: rejects import of non-exported name from relative module", () => {
    expect(() =>
      compileGraph({
        roots: ["/root.ts"],
        readFile: makeReadFile({
          "/root.ts": `
            import { doesNotExist } from "./helper.ts";
            export function* main() { return 1; }
          `,
          "/helper.ts": `
            export function* helper() { return 42; }
          `,
        }),
        validate: false,
      }),
    ).toThrow(/E-IMPORT-005/);
  });

  it("allows resource/provide imported from bare specifier (compiler intrinsics)", () => {
    const result = compileGraph({
      roots: ["/root.ts"],
      readFile: makeReadFile({
        "/root.ts": `
          import { resource, provide } from "@tisyn/agent";
          declare function Svc(): {
            open(cfg: { model: string }): Workflow<{ id: string }>;
            close(handle: { id: string }): Workflow<void>;
          };
          export function* main() {
            return yield* resource(function* () {
              const handle = yield* Svc().open({ model: "test" });
              try {
                yield* provide(handle);
              } finally {
                yield* Svc().close(handle);
              }
            });
          }
        `,
      }),
      validate: false,
    });

    expect(result.source).toBeDefined();
    expect(result.graph.compiled).toContain("main");
  });

  it("still rejects non-intrinsic value imports from bare specifier (E-IMPORT-001)", () => {
    expect(() =>
      compileGraph({
        roots: ["/root.ts"],
        readFile: makeReadFile({
          "/root.ts": `
            import { resource, someUtility } from "@tisyn/agent";
            export function* main() { return someUtility(); }
          `,
        }),
        validate: false,
      }),
    ).toThrow(/E-IMPORT-001/);
  });

  it("allows bare specifier import when not referenced in reachable code", () => {
    const result = compileGraph({
      roots: ["/root.ts"],
      readFile: makeReadFile({
        "/root.ts": `
          import { readFile } from "node:fs";
          export function* main() { return 1; }
        `,
      }),
      validate: false,
    });
    expect(result.source).toBeDefined();
  });
});

// ── resource() in non-generator helper ──

describe("resource in non-generator helper", () => {
  const resourceHelperFiles = {
    "/root.ts": `
      function useSession() {
        return resource(function* () {
          yield* provide(42);
        });
      }
      export function* main() {
        return yield* useSession();
      }
    `,
  };

  it("compileGraph: non-generator helper returning resource() compiles successfully", () => {
    const result = compileGraph({
      roots: ["/root.ts"],
      readFile: makeReadFile(resourceHelperFiles),
      validate: false,
    });

    expect(result.graph.compiled).toContain("main");
    expect(result.graph.compiled.length).toBe(2);
    expect(result.source).toContain("Resource(");
  });

  it("compileGraphForRuntime: same pattern succeeds through runtime path", () => {
    const result = compileGraphForRuntime({
      roots: ["/root.ts"],
      readFile: makeReadFile(resourceHelperFiles),
      validate: false,
      exportName: "main",
    });

    expect(result.ir).toBeDefined();
    expect(result.runtimeBindings).toBeDefined();
  });

  it("rejects nested resource() via bare call with RS7", () => {
    expect(() =>
      compileGraph({
        roots: ["/root.ts"],
        readFile: makeReadFile({
          "/root.ts": `
            function nestedResource() {
              return resource(function* () {
                yield* provide(resource(function* () {
                  yield* provide(1);
                }));
              });
            }
            export function* main() {
              return yield* nestedResource();
            }
          `,
        }),
        validate: false,
      }),
    ).toThrow(/RS7/);
  });
});

// ── Warnings (W-GRAPH-001) ──

describe("W-GRAPH-001 unreachable export warnings", () => {
  it("warns for exported non-entrypoint symbol not called from any entrypoint", () => {
    // helper.ts has a generator (making it workflow-implementation) plus an
    // exported non-generator function that is never called from any entrypoint.
    const result = compileGraph({
      roots: ["/root.ts"],
      readFile: makeReadFile({
        "/root.ts": `
          import { used } from "./helper.ts";
          export function* main() { yield* used(); }
        `,
        "/helper.ts": `
          export function* used() { return 1; }
          export function notCalled() { return 2; }
        `,
      }),
      validate: false,
    });

    expect(result.warnings.length).toBeGreaterThan(0);
    expect(result.warnings.some((w) => w.includes("W-GRAPH-001") && w.includes("notCalled"))).toBe(
      true,
    );
  });

  it("does not warn for entrypoint functions", () => {
    const result = compileGraph({
      roots: ["/root.ts"],
      readFile: makeReadFile({
        "/root.ts": `
          export function* main() { return 1; }
        `,
      }),
      validate: false,
    });

    expect(result.warnings).toEqual([]);
  });

  it("warning ordering is deterministic", () => {
    const files = {
      "/root.ts": `
        export function* main() { return 1; }
        export function* alpha() { return 2; }
        export function* beta() { return 3; }
      `,
    };
    const opts = { roots: ["/root.ts"], readFile: makeReadFile(files), validate: false };
    const w1 = compileGraph(opts).warnings;
    const w2 = compileGraph(opts).warnings;
    expect(w1).toEqual(w2);
  });
});

// ── Module reclassification (§15.7) ──

describe("module reclassification", () => {
  it("MC8: reclassifies workflow-implementation to external when no generators and no compiled symbols", () => {
    const result = compileGraph({
      roots: ["/root.ts"],
      readFile: makeReadFile({
        "/root.ts": `
          import { config } from "./utils.ts";
          export function* main() { return 1; }
        `,
        "/utils.ts": `
          export const config = { key: "value" };
        `,
      }),
      validate: false,
    });

    expect(result.graph.modules["/utils.ts"]?.category).toBe("external");
  });
});

// ── Generated-module modeling (GM3/GM4/GM5) ──

describe("generated-module symbol modeling", () => {
  it("GM3: extracts function signatures from generated modules", () => {
    const result = compileGraph({
      roots: ["/src/root.ts"],
      readFile: makeReadFile({
        "/src/root.ts": `
          import { helper } from "./generated.ts";
          export function* main() { return yield* helper(); }
        `,
        "/src/generated.ts": [
          "// Auto-generated by @tisyn/compiler",
          "export function* helper() { return 42; }",
        ].join("\n"),
      }),
      outputPath: "/src/output.generated.ts",
      validate: false,
    });

    expect(result.graph.modules["/src/generated.ts"]?.category).toBe("generated");
    const importLine = result.source.split("\n").find((l) => l.includes("generated.ts"));
    expect(importLine).toBe('import { helper } from "./generated.ts";');
  });

  it("GM8: does not recompile generated-module functions", () => {
    const result = compileGraph({
      roots: ["/src/root.ts"],
      readFile: makeReadFile({
        "/src/root.ts": `
          import { helper } from "./generated.ts";
          export function* main() { return yield* helper(); }
        `,
        "/src/generated.ts": [
          "// Auto-generated by @tisyn/compiler",
          "export function* helper() { return 42; }",
        ].join("\n"),
      }),
      outputPath: "/src/output.generated.ts",
      validate: false,
    });

    // helper should NOT appear in compiled symbols — it's a generated module
    expect(result.graph.compiled).not.toContain("helper");
    // But the import should be emitted as a relative specifier
    const importLine = result.source.split("\n").find((l) => l.includes("generated.ts"));
    expect(importLine).toBe('import { helper } from "./generated.ts";');
  });

  it("GM4: resolves non-function exports from generated modules", () => {
    const result = compileGraph({
      roots: ["/src/root.ts"],
      readFile: makeReadFile({
        "/src/root.ts": `
          import { MyAgent } from "./generated.ts";
          export function* main() { return MyAgent(); }
        `,
        "/src/generated.ts": [
          "// Auto-generated by @tisyn/compiler",
          "export function MyAgent() { return {}; }",
        ].join("\n"),
      }),
      outputPath: "/src/output.generated.ts",
      validate: false,
    });

    const importLine = result.source.split("\n").find((l) => l.includes("generated.ts"));
    expect(importLine).toBe('import { MyAgent } from "./generated.ts";');
  });

  it("AI-GEN-001: emits relative import specifier for generated module", () => {
    const result = compileGraph({
      roots: ["/app/src/root.ts"],
      readFile: makeReadFile({
        "/app/src/root.ts": `
          import { helper } from "../lib/prior.generated.ts";
          export function* main() { return yield* helper(); }
        `,
        "/app/lib/prior.generated.ts": [
          "// Auto-generated by @tisyn/compiler",
          "export function* helper() { return 42; }",
        ].join("\n"),
      }),
      outputPath: "/app/src/workflow.generated.ts",
      validate: false,
    });

    const importLine = result.source.split("\n").find((l) => l.includes("prior.generated.ts"));
    expect(importLine).toBe('import { helper } from "../lib/prior.generated.ts";');
  });

  it("AI-GEN-002: changing generated module content produces different output", () => {
    const makeFiles = (helperBody: string) => ({
      "/src/root.ts": `
        import { helper } from "./generated.ts";
        export function* main() { return yield* helper(); }
      `,
      "/src/generated.ts": [
        "// Auto-generated by @tisyn/compiler",
        `export function* helper() { return ${helperBody}; }`,
      ].join("\n"),
    });

    const opts = { outputPath: "/src/output.generated.ts", validate: false } as const;
    const r1 = compileGraph({
      roots: ["/src/root.ts"],
      readFile: makeReadFile(makeFiles("42")),
      ...opts,
    });
    const r2 = compileGraph({
      roots: ["/src/root.ts"],
      readFile: makeReadFile(makeFiles("99")),
      ...opts,
    });

    // The generated-module functions are not recompiled, so the output
    // artifact doesn't change based on generated module body content.
    // But the import line should be present in both as a relative specifier.
    const line1 = r1.source.split("\n").find((l) => l.includes("generated.ts"));
    const line2 = r2.source.split("\n").find((l) => l.includes("generated.ts"));
    expect(line1).toBe('import { helper } from "./generated.ts";');
    expect(line2).toBe('import { helper } from "./generated.ts";');
  });

  it("emits relative specifier without explicit outputPath (falls back to root directory)", () => {
    const result = compileGraph({
      roots: ["/project/src/root.ts"],
      readFile: makeReadFile({
        "/project/src/root.ts": `
          import { helper } from "./prior.generated.ts";
          export function* main() { return yield* helper(); }
        `,
        "/project/src/prior.generated.ts": [
          "// Auto-generated by @tisyn/compiler",
          "export function* helper() { return 42; }",
        ].join("\n"),
      }),
      // no outputPath — must still produce a relative specifier
      validate: false,
    });

    const importLine = result.source.split("\n").find((l) => l.includes("prior.generated.ts"));
    expect(importLine).toBe('import { helper } from "./prior.generated.ts";');
    // Guard: no absolute paths in any import line
    const importLines = result.source.split("\n").filter((l) => l.startsWith("import "));
    for (const line of importLines) {
      expect(line).not.toMatch(/from "\/[^.]/);
    }
  });

  it("never emits absolute filesystem paths in generated-module imports", () => {
    const result = compileGraph({
      roots: ["/users/dev/project/src/workflow.ts"],
      readFile: makeReadFile({
        "/users/dev/project/src/workflow.ts": `
          import { Agent } from "../gen/agents.generated.ts";
          export function* main() { return Agent(); }
        `,
        "/users/dev/project/gen/agents.generated.ts": [
          "// Auto-generated by @tisyn/compiler",
          "export function Agent() { return {}; }",
        ].join("\n"),
      }),
      outputPath: "/users/dev/project/src/workflow.generated.ts",
      validate: false,
    });

    const importLine = result.source.split("\n").find((l) => l.includes("agents.generated.ts"));
    expect(importLine).toBe('import { Agent } from "../gen/agents.generated.ts";');
    // Must not contain any absolute path fragments
    expect(importLine).not.toContain("/users/dev");
  });

  it("emits POSIX forward-slash separators in generated-module import specifiers", () => {
    // Simulate a cross-directory generated import where path.relative would
    // produce backslashes on Windows (e.g. "..\\generated\\prior.generated.ts").
    // The compiler must normalize to forward slashes for valid ESM specifiers.
    const result = compileGraph({
      roots: ["/project/src/root.ts"],
      readFile: makeReadFile({
        "/project/src/root.ts": `
          import { MyAgent } from "../generated/prior.generated.ts";
          export function* main() { return MyAgent(); }
        `,
        "/project/generated/prior.generated.ts": [
          "// Auto-generated by @tisyn/compiler",
          "export function MyAgent() { return {}; }",
        ].join("\n"),
      }),
      outputPath: "/project/src/output.generated.ts",
      validate: false,
    });

    const importLine = result.source.split("\n").find((l) => l.includes("prior.generated.ts"));
    expect(importLine).toBe('import { MyAgent } from "../generated/prior.generated.ts";');
    // Must never contain backslashes — invalid in ESM specifiers
    expect(importLine).not.toContain("\\");
  });
});

// ── Contract-workflow name collision ──

describe("contract-symbol name conflicts", () => {
  it("rejects workflow name that collides with contract name", () => {
    expect(() =>
      compileGraph({
        roots: ["/root.ts"],
        readFile: makeReadFile({
          "/root.ts": `
            declare function Svc(): {
              fetch(id: string): Workflow<string>;
            };
            export function* Svc() { return 1; }
          `,
        }),
        validate: false,
      }),
    ).toThrow(/collides with contract name/);
  });
});

// ── JSON determinism ──

describe("JSON determinism", () => {
  it("JSON format output is identical regardless of source declaration order", () => {
    // Two files with declarations in different orders
    const fileSetA = {
      "/root.ts": `
        export function* alpha(x: number) { return x; }
        export function* beta(a: string, b: number) { return a; }
      `,
    };
    const fileSetB = {
      "/root.ts": `
        export function* beta(a: string, b: number) { return a; }
        export function* alpha(x: number) { return x; }
      `,
    };

    const rA = compileGraph({
      roots: ["/root.ts"],
      readFile: makeReadFile(fileSetA),
      validate: false,
      format: "json",
    });
    const rB = compileGraph({
      roots: ["/root.ts"],
      readFile: makeReadFile(fileSetB),
      validate: false,
      format: "json",
    });

    expect(rA.source).toBe(rB.source);
  });
});

// ── Runtime binding resolution (compileGraphForRuntime) ──

describe("runtime binding resolution", () => {
  it("RT-001: same-file helper produces selected export and helper in runtimeBindings", () => {
    const result = compileGraphForRuntime({
      roots: ["/root.ts"],
      readFile: makeReadFile({
        "/root.ts": `
          function* helper() { return 42; }
          export function* main() { return yield* helper(); }
        `,
      }),
      validate: false,
      exportName: "main",
    });

    expect(result.runtimeBindings["__rtexport_main"]).toBeDefined();
    const helperKeys = Object.keys(result.runtimeBindings).filter((k) => k.includes("helper"));
    expect(helperKeys.length).toBe(1);
    expect(helperKeys[0]).toMatch(/^__m\d+_helper$/);

    // The rewritten IR should reference the helper's emitted name, not "helper"
    const refs = collectRefs(result.ir);
    expect(refs).not.toContain("helper");
    expect(refs.some((r) => r.match(/^__m\d+_helper$/))).toBe(true);
  });

  it("RT-002: cross-module import produces both symbols in runtimeBindings", () => {
    const result = compileGraphForRuntime({
      roots: ["/root.ts"],
      readFile: makeReadFile({
        "/root.ts": `
          import { helper } from "./utils.ts";
          export function* main() { return yield* helper(); }
        `,
        "/utils.ts": `
          export function* helper() { return 42; }
        `,
      }),
      validate: false,
      exportName: "main",
    });

    expect(result.runtimeBindings["__rtexport_main"]).toBeDefined();
    expect(result.runtimeBindings["__rtexport_helper"]).toBeDefined();
  });

  it("RT-003: aliased import resolves to target's runtime name", () => {
    const result = compileGraphForRuntime({
      roots: ["/root.ts"],
      readFile: makeReadFile({
        "/root.ts": `
          import { helper as h } from "./utils.ts";
          export function* main() { return yield* h(); }
        `,
        "/utils.ts": `
          export function* helper() { return 42; }
        `,
      }),
      validate: false,
      exportName: "main",
    });

    // The alias "h" should be resolved to __rtexport_helper
    const refs = collectRefs(result.ir);
    expect(refs).not.toContain("h");
    expect(refs).not.toContain("helper");
    expect(result.runtimeBindings["__rtexport_helper"]).toBeDefined();
    expect(result.runtimeBindings["__rtexport_main"]).toBeDefined();
  });

  it("RT-004: two modules with same-named non-exported helper get distinct bindings", () => {
    const result = compileGraphForRuntime({
      roots: ["/root.ts"],
      readFile: makeReadFile({
        "/root.ts": `
          import { processA } from "./a.ts";
          import { processB } from "./b.ts";
          export function* main() {
            const a = yield* processA();
            const b = yield* processB();
            return a;
          }
        `,
        "/a.ts": `
          function* helper() { return 1; }
          export function* processA() { return yield* helper(); }
        `,
        "/b.ts": `
          function* helper() { return 2; }
          export function* processB() { return yield* helper(); }
        `,
      }),
      validate: false,
      exportName: "main",
    });

    expect(result.runtimeBindings["__rtexport_main"]).toBeDefined();
    expect(result.runtimeBindings["__rtexport_processA"]).toBeDefined();
    expect(result.runtimeBindings["__rtexport_processB"]).toBeDefined();

    // Two distinct helper bindings
    const helperKeys = Object.keys(result.runtimeBindings).filter((k) => k.includes("helper"));
    expect(helperKeys.length).toBe(2);
    expect(helperKeys[0]).not.toBe(helperKeys[1]);
  });

  it("RT-005: per-export scoping excludes unrelated workflow's closure", () => {
    const result = compileGraphForRuntime({
      roots: ["/root.ts"],
      readFile: makeReadFile({
        "/root.ts": `
          function* helperA() { return 1; }
          function* helperB() { return 2; }
          export function* workflowA() { return yield* helperA(); }
          export function* workflowB() { return yield* helperB(); }
        `,
      }),
      validate: false,
      exportName: "workflowA",
    });

    expect(result.runtimeBindings["__rtexport_workflowA"]).toBeDefined();
    const helperAKeys = Object.keys(result.runtimeBindings).filter((k) => k.includes("helperA"));
    expect(helperAKeys.length).toBe(1);

    // workflowB and helperB should NOT be included
    expect(result.runtimeBindings["__rtexport_workflowB"]).toBeUndefined();
    const helperBKeys = Object.keys(result.runtimeBindings).filter((k) => k.includes("helperB"));
    expect(helperBKeys.length).toBe(0);
  });

  it("RT-006: exported helper referenced by renamed export uses target's runtime name", () => {
    const result = compileGraphForRuntime({
      roots: ["/root.ts"],
      readFile: makeReadFile({
        "/root.ts": `
          import { myHelper } from "./utils.ts";
          export function* main() { return yield* myHelper(); }
        `,
        "/utils.ts": `
          function* helper() { return 42; }
          export { helper as myHelper };
        `,
      }),
      validate: false,
      exportName: "main",
    });

    expect(result.runtimeBindings["__rtexport_myHelper"]).toBeDefined();
    expect(result.runtimeBindings["__rtexport_main"]).toBeDefined();
  });
});
