/**
 * Module graph construction, classification, and symbol extraction.
 *
 * All types in this module are internal implementation details.
 * Nothing from graph.ts is re-exported through the package's public API.
 *
 * Implements amendment sections §14 (Graph Construction), §15 (Module Classification),
 * and §16.1 (Symbol Extraction).
 */

import ts from "typescript";
import { dirname, resolve, extname } from "node:path";
import { discoverContracts, type DiscoveredContract } from "./discover.js";
import {
  parseGenerators,
  parseNonGeneratorFunctions,
  parseConstBoundGenerators,
  collectAllExportedNames,
  type ParsedFunction,
  type ParsedNonGeneratorFunction,
  type ModuleExports,
} from "./parse.js";
import { CompileError } from "./errors.js";

// ── Public types (internal to compiler package) ──

export type ModuleCategory =
  | "workflow-implementation"
  | "contract-declaration"
  | "generated"
  | "type-only"
  | "external";

export interface ValueImport {
  localName: string;
  importedName: string;
  fromModule: string;
  /** Resolved absolute path of the target module. */
  resolvedPath: string;
}

export interface ModuleInfo {
  path: string;
  category: ModuleCategory;
  sourceFile: ts.SourceFile;
  generators: ParsedFunction[];
  nonGeneratorFunctions: ParsedNonGeneratorFunction[];
  discoveredContracts: DiscoveredContract[];
  exportMap: ModuleExports;
  valueImports: ValueImport[];
  /** Raw type-only import declaration text for forwarding to output. */
  typeImportTexts: string[];
}

export interface GraphResult {
  modules: Map<string, ModuleInfo>;
  /** Modules in order of traversal (lexicographic by resolved path). */
  traversalOrder: string[];
}

// ── Auto-generated banner ──

const GENERATED_BANNER = "// Auto-generated by @tisyn/compiler";

// ── Graph construction (§14) ──

/**
 * Build the module graph starting from root module paths.
 *
 * Implements the G1-G8 algorithm from amendment section 14.
 */
export function buildGraph(
  roots: string[],
  readFile: (path: string) => string,
  generatedModulePaths?: string[],
): GraphResult {
  if (roots.length === 0) {
    throw new CompileError("E-GRAPH-001", "No roots provided", 1, 1);
  }

  const generatedSet = new Set(generatedModulePaths ?? []);
  const modules = new Map<string, ModuleInfo>();
  const visited = new Set<string>();

  // G1: Parse each root module
  for (const root of roots) {
    traverseModule(root, readFile, generatedSet, modules, visited);
  }

  // Build traversal order: lexicographic by resolved path
  const traversalOrder = [...modules.keys()].sort();

  return { modules, traversalOrder };
}

function traverseModule(
  modulePath: string,
  readFile: (path: string) => string,
  generatedSet: Set<string>,
  modules: Map<string, ModuleInfo>,
  visited: Set<string>,
): void {
  // G8 / §14.3: Cycle handling via visited set
  if (visited.has(modulePath)) { return; }
  visited.add(modulePath);

  // Read source
  let source: string;
  try {
    source = readFile(modulePath);
  } catch (err) {
    throw new CompileError(
      "E-IMPORT-003",
      `Cannot read module '${modulePath}': ${err instanceof Error ? err.message : String(err)}`,
      1,
      1,
    );
  }

  // Parse
  const sourceFile = ts.createSourceFile(
    modulePath,
    source,
    ts.ScriptTarget.Latest,
    true,
    modulePath.endsWith(".ts") || modulePath.endsWith(".mts") || modulePath.endsWith(".cts")
      ? ts.ScriptKind.TS
      : ts.ScriptKind.JS,
  );

  // Extract imports
  const { valueImports, typeImportTexts, rejections, typeOnlyModulePaths, externalSpecifiers } =
    extractImports(sourceFile, modulePath);

  // Apply import rejections
  if (rejections.length > 0) {
    const r = rejections[0]!;
    throw new CompileError(r.code, r.message, r.line, r.column);
  }

  // Classify module
  const category = classifyModule(sourceFile, modulePath, generatedSet, source);

  // Extract symbols based on category
  const generators = category === "generated" || category === "type-only" || category === "external"
    ? []
    : [...parseGenerators(sourceFile), ...parseConstBoundGenerators(sourceFile)];

  const nonGeneratorFunctions =
    category === "generated" || category === "type-only" || category === "external"
      ? []
      : parseNonGeneratorFunctions(sourceFile);

  const discoveredContracts =
    category === "generated" || category === "type-only" || category === "external"
      ? []
      : discoverContracts(sourceFile).contracts;

  const exportMap = collectAllExportedNames(sourceFile);

  const info: ModuleInfo = {
    path: modulePath,
    category,
    sourceFile,
    generators,
    nonGeneratorFunctions,
    discoveredContracts,
    exportMap,
    valueImports,
    typeImportTexts,
  };

  modules.set(modulePath, info);

  // Record boundary modules (type-only and external) without traversal
  for (const typePath of typeOnlyModulePaths) {
    if (!modules.has(typePath)) {
      modules.set(typePath, makeBoundaryModule(typePath, "type-only"));
    }
  }
  for (const specifier of externalSpecifiers) {
    if (!modules.has(specifier)) {
      modules.set(specifier, makeBoundaryModule(specifier, "external"));
    }
  }

  // G4: Recursively traverse workflow-implementation and contract-declaration modules
  if (category === "workflow-implementation" || category === "contract-declaration") {
    for (const imp of valueImports) {
      traverseModule(imp.resolvedPath, readFile, generatedSet, modules, visited);
    }
  }
  // G5: Generated → export names extracted, stop traversal
  // G6: Type-only → recorded, stop traversal
  // G7: External → recorded, stop traversal
}

/**
 * Create a stub ModuleInfo for a boundary module that is not traversed.
 */
function makeBoundaryModule(path: string, category: "type-only" | "external"): ModuleInfo {
  const emptySource = ts.createSourceFile(path, "", ts.ScriptTarget.Latest, true, ts.ScriptKind.TS);
  return {
    path,
    category,
    sourceFile: emptySource,
    generators: [],
    nonGeneratorFunctions: [],
    discoveredContracts: [],
    exportMap: { local: new Map(), reExports: [] },
    valueImports: [],
    typeImportTexts: [],
  };
}

// ── Module classification (§15) ──

/**
 * Classify a module into one of five categories.
 *
 * This is the Stage 2 tentative classification. Modules with only
 * non-generator functions may be reclassified after Stage 5.
 */
function classifyModule(
  sourceFile: ts.SourceFile,
  path: string,
  generatedSet: Set<string>,
  source: string,
): ModuleCategory {
  // GM1: Build-configuration declaration (§20.2)
  if (generatedSet.has(path)) {
    return "generated";
  }

  // GM2: Content-based heuristic — auto-generated banner (§20.2)
  if (source.startsWith(GENERATED_BANNER)) {
    return "generated";
  }

  // Check for generators (MC1)
  let hasGenerators = false;
  let hasContractDeclarations = false;
  let hasFunctionDeclarations = false;
  let hasConstBoundFunctions = false;

  for (const stmt of sourceFile.statements) {
    if (ts.isFunctionDeclaration(stmt)) {
      if (stmt.asteriskToken && stmt.name && stmt.body) {
        hasGenerators = true;
      } else if (stmt.name && stmt.body && !stmt.asteriskToken) {
        hasFunctionDeclarations = true;
      }
      // Check for ambient contract declaration
      if (
        !stmt.body &&
        stmt.modifiers?.some((m) => m.kind === ts.SyntaxKind.DeclareKeyword)
      ) {
        // Quick check: does it look like a contract? (declare function with return type literal)
        if (stmt.type && ts.isTypeLiteralNode(stmt.type)) {
          hasContractDeclarations = true;
        }
        // Also handle factory pattern: declare function Name(instance?: string): { ... }
        if (stmt.type && ts.isFunctionTypeNode(stmt.type)) {
          hasContractDeclarations = true;
        }
      }
    }

    if (ts.isVariableStatement(stmt) && (stmt.declarationList.flags & ts.NodeFlags.Const)) {
      for (const decl of stmt.declarationList.declarations) {
        if (!decl.initializer) { continue; }
        if (ts.isFunctionExpression(decl.initializer)) {
          if (decl.initializer.asteriskToken) {
            hasGenerators = true;
          } else {
            hasConstBoundFunctions = true;
          }
        }
        if (ts.isArrowFunction(decl.initializer)) {
          hasConstBoundFunctions = true;
        }
      }
    }
  }

  // MC1: Contains generators → workflow-implementation
  if (hasGenerators) {
    return "workflow-implementation";
  }

  // MC3: Contains contract declarations and no generators
  if (hasContractDeclarations) {
    // May be reclassified to workflow-implementation after Stage 5 if
    // non-generator functions qualify as expression helpers (MP2).
    return "contract-declaration";
  }

  // MC2/MC7/MC8: Has non-generator functions — tentatively classify
  // as workflow-implementation. If none qualify at Stage 5, it will
  // be reclassified to external.
  if (hasFunctionDeclarations || hasConstBoundFunctions) {
    return "workflow-implementation";
  }

  // MC7: No functions, no contracts → external
  return "external";
}

// ── Import extraction ──

interface ImportRejection {
  code: string;
  message: string;
  line: number;
  column: number;
}

interface ExtractedImports {
  valueImports: ValueImport[];
  typeImportTexts: string[];
  rejections: ImportRejection[];
  /** Resolved paths of type-only import targets (boundary, no traversal). */
  typeOnlyModulePaths: string[];
  /** Bare specifier / node: protocol identifiers (boundary, no traversal). */
  externalSpecifiers: string[];
}

/**
 * Extract and validate import declarations from a source file.
 *
 * Implements §2.3 Import Semantics (IS1-IS9).
 */
export function extractImports(
  sourceFile: ts.SourceFile,
  modulePath: string,
): ExtractedImports {
  const valueImports: ValueImport[] = [];
  const typeImportTexts: string[] = [];
  const rejections: ImportRejection[] = [];
  const typeOnlyModulePaths: string[] = [];
  const externalSpecifiers: string[] = [];
  const moduleDir = dirname(modulePath);

  for (const stmt of sourceFile.statements) {
    if (!ts.isImportDeclaration(stmt)) {
      // Check for dynamic imports in expression statements
      continue;
    }

    const specifierText = stmt.moduleSpecifier.getText(sourceFile).slice(1, -1);
    const loc = getNodeLocation(stmt, sourceFile);

    // Check import clause type
    const clause = stmt.importClause;
    if (!clause) { continue; } // side-effect import — skip

    // IS2: Type-only imports — forward without resolution
    if (clause.isTypeOnly) {
      typeImportTexts.push(stmt.getText(sourceFile));
      const isRelative = specifierText.startsWith("./") || specifierText.startsWith("../");
      if (isRelative && extname(specifierText)) {
        typeOnlyModulePaths.push(resolve(moduleDir, specifierText));
      }
      continue;
    }

    // IS6: Default import — reject
    if (clause.name) {
      rejections.push({
        code: "E-IMPORT-007",
        message: `Default import is not supported: import ${clause.name.text} from "${specifierText}"`,
        ...loc,
      });
      continue;
    }

    const namedBindings = clause.namedBindings;

    // IS7: Namespace import — reject
    if (namedBindings && ts.isNamespaceImport(namedBindings)) {
      rejections.push({
        code: "E-IMPORT-007",
        message: `Namespace import is not supported: import * as ${namedBindings.name.text} from "${specifierText}"`,
        ...loc,
      });
      continue;
    }

    // Must be named imports (IS1)
    if (!namedBindings || !ts.isNamedImports(namedBindings)) { continue; }

    // Classify specifier
    const isRelative = specifierText.startsWith("./") || specifierText.startsWith("../");

    if (!isRelative) {
      // IS5/IS5a/R2/R3: Bare specifier or node: protocol — graph boundary
      // Individual type-only elements are OK (IS9), but value elements are boundaries
      let hasValueBindings = false;
      for (const el of namedBindings.elements) {
        if (!el.isTypeOnly) {
          hasValueBindings = true;
          break;
        }
      }

      if (hasValueBindings) {
        // Record as external boundary
        externalSpecifiers.push(specifierText);
        continue;
      }

      // All type-only — forward
      typeImportTexts.push(stmt.getText(sourceFile));
      continue;
    }

    // Relative specifier — validate extension (R4)
    if (!extname(specifierText)) {
      rejections.push({
        code: "E-IMPORT-002",
        message: `Import specifier '${specifierText}' is missing a file extension`,
        ...loc,
      });
      continue;
    }

    // Resolve path (R1)
    const resolvedPath = resolve(moduleDir, specifierText);

    // Extract named value imports (IS1)
    for (const el of namedBindings.elements) {
      if (el.isTypeOnly) { continue; }

      const importedName = el.propertyName?.text ?? el.name.text;
      const localName = el.name.text;

      valueImports.push({
        localName,
        importedName,
        fromModule: specifierText,
        resolvedPath,
      });
    }
  }

  // Scan for dynamic imports (IS3 — E-IMPORT-006)
  scanForDynamicImports(sourceFile, rejections);

  // Scan for re-exports (IS8 — E-IMPORT-007)
  scanForReExports(sourceFile, rejections);

  return { valueImports, typeImportTexts, rejections, typeOnlyModulePaths, externalSpecifiers };
}

function scanForDynamicImports(
  sourceFile: ts.SourceFile,
  rejections: ImportRejection[],
): void {
  function visit(node: ts.Node): void {
    if (
      ts.isCallExpression(node) &&
      node.expression.kind === ts.SyntaxKind.ImportKeyword
    ) {
      const loc = getNodeLocation(node, sourceFile);
      rejections.push({
        code: "E-IMPORT-006",
        message: "Dynamic import expressions are not allowed in workflow code",
        ...loc,
      });
    }
    ts.forEachChild(node, visit);
  }
  ts.forEachChild(sourceFile, visit);
}

function scanForReExports(
  sourceFile: ts.SourceFile,
  rejections: ImportRejection[],
): void {
  for (const stmt of sourceFile.statements) {
    if (
      ts.isExportDeclaration(stmt) &&
      stmt.moduleSpecifier &&
      !stmt.isTypeOnly
    ) {
      // Check if any elements are value (non-type-only) re-exports
      if (stmt.exportClause && ts.isNamedExports(stmt.exportClause)) {
        const hasValueReExports = stmt.exportClause.elements.some((el) => !el.isTypeOnly);
        if (hasValueReExports) {
          const loc = getNodeLocation(stmt, sourceFile);
          rejections.push({
            code: "E-IMPORT-007",
            message: `Re-export is not supported: ${stmt.getText(sourceFile)}`,
            ...loc,
          });
        }
      } else if (!stmt.exportClause) {
        // export * from "..." — also unsupported
        const loc = getNodeLocation(stmt, sourceFile);
        rejections.push({
          code: "E-IMPORT-007",
          message: `Star re-export is not supported: ${stmt.getText(sourceFile)}`,
          ...loc,
        });
      }
    }
  }
}

function getNodeLocation(
  node: ts.Node,
  sourceFile: ts.SourceFile,
): { line: number; column: number } {
  const { line, character } = sourceFile.getLineAndCharacterOfPosition(node.getStart(sourceFile));
  return { line: line + 1, column: character + 1 };
}
