export { compile, compileOne, type CompileOptions, type CompileResult } from "./compile.js";
export { generateWorkflowModule, type GenerateOptions, type GenerateResult } from "./generate.js";
export type { DiscoveredContract, ContractMethod } from "./discover.js";
export { toAgentId } from "./agent-id.js";
export { Counter } from "./counter.js";
export { CompileError, ErrorCodes } from "./errors.js";
export {
  Q,
  Ref,
  Fn,
  Let,
  Seq,
  If,
  While,
  Call,
  Get,
  Add,
  Sub,
  Mul,
  Div,
  Mod,
  Gt,
  Gte,
  Lt,
  Lte,
  Eq,
  Neq,
  And,
  Or,
  Not,
  Neg,
  Construct,
  ArrayNode,
  Concat,
  Throw,
  ExternalEval,
  AllEval,
  RaceEval,
  ScopeEval,
  SpawnEval,
  JoinEval,
  ResourceEval,
  ProvideEval,
  TimeboxEval,
} from "./ir-builders.js";
