/**
 * Descriptor and workflow module loading for `tsn run` and `tsn check`.
 *
 * Loads workflow descriptors, resolves workflow modules, and extracts
 * compiled IR exports with input schema metadata.
 */

import { readFile } from "node:fs/promises";
import { resolve, dirname } from "node:path";
import { call } from "effection";
import type { Operation } from "effection";
import { loadModule } from "./load-module.js";
import { isTypeScriptFile } from "./load-module.js";
import type { TisynExpr as Expr } from "@tisyn/ir";
import { compileGraphForRuntime, CompileError } from "@tisyn/compiler";
import type { InputSchema } from "@tisyn/compiler";
import type { WorkflowDescriptor } from "@tisyn/config";

export interface WorkflowExport {
  ir: Expr;
  inputSchema?: InputSchema;
  /** Compiler-provided runtime bindings for reachable compiled symbols. */
  runtimeBindings?: Record<string, Expr>;
}

/**
 * Dynamically import a module and extract its default export as a WorkflowDescriptor.
 *
 * Exit codes:
 * - 3: module not found / import error
 * - 2: no default export or not a valid WorkflowDescriptor
 */
export function* loadDescriptorModule(modulePath: string): Operation<WorkflowDescriptor> {
  const mod = yield* loadModule(modulePath);

  const descriptor = mod.default;
  if (!descriptor || typeof descriptor !== "object") {
    throw new CliError(2, `Module '${modulePath}' has no default export`);
  }

  if ((descriptor as Record<string, unknown>).tisyn_config !== "workflow") {
    throw new CliError(
      2,
      `Default export of '${modulePath}' is not a WorkflowDescriptor (missing tisyn_config: "workflow")`,
    );
  }

  return descriptor as WorkflowDescriptor;
}

/**
 * Resolve the workflow module path and export name from a descriptor.
 *
 * `run` is a WorkflowRef: `{ export, module? }`.
 * If `module` is present, resolve it relative to the descriptor path.
 * Otherwise, the descriptor module itself contains the workflow export.
 */
export function resolveWorkflowModule(
  descriptor: WorkflowDescriptor,
  descriptorPath: string,
): { modulePath: string; exportName: string; explicit: boolean } {
  const run = descriptor.run;
  const exportName = run.export;
  const explicit = !!run.module;
  const modulePath = run.module ? resolve(dirname(descriptorPath), run.module) : descriptorPath;
  return { modulePath, exportName, explicit };
}

/**
 * Load a workflow IR export and optional input schema from a generated module.
 *
 * Exit codes:
 * - 3: module import failure
 * - 2: named export not found or structurally invalid
 */
export function* loadWorkflowExport(
  modulePath: string,
  exportName: string,
): Operation<WorkflowExport> {
  const mod = yield* loadModule(modulePath);

  const ir = mod[exportName];
  if (!ir || typeof ir !== "object") {
    throw new CliError(2, `Workflow module '${modulePath}' does not export '${exportName}'`);
  }

  if (
    (ir as Record<string, unknown>).tisyn !== "fn" &&
    (ir as Record<string, unknown>).tisyn !== "eval"
  ) {
    throw new CliError(2, `Export '${exportName}' in '${modulePath}' is not a valid Tisyn IR node`);
  }

  // Attempt to load input schema metadata
  let inputSchema: InputSchema | undefined;
  const inputSchemas = mod.inputSchemas as Record<string, InputSchema> | undefined;
  if (inputSchemas && typeof inputSchemas === "object" && exportName in inputSchemas) {
    inputSchema = inputSchemas[exportName];
  }

  return { ir: ir as Expr, inputSchema };
}

/**
 * Resolve a workflow module to a WorkflowExport.
 *
 * Applies the three-step dispatch rule:
 *   1. Non-TypeScript → load at runtime
 *   2. TypeScript with compiler banner → load at runtime
 *   3. TypeScript source → compile, write temp artifact, load
 */
export function* resolveWorkflowExport(
  workflowPath: string,
  exportName: string,
): Operation<WorkflowExport> {
  // Rule 1: .js/.mjs/.cjs → pre-compiled, load at runtime
  if (!isTypeScriptFile(workflowPath)) {
    return yield* loadWorkflowExport(workflowPath, exportName);
  }

  // Read the file to check for compiler banner
  let content: string;
  try {
    content = yield* call(() => readFile(workflowPath, "utf-8"));
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    throw new CliError(3, `Failed to read workflow source '${workflowPath}': ${msg}`);
  }

  // Rule 2: .ts with auto-generated banner → prior compiler output, load at runtime
  if (content.startsWith("// Auto-generated by @tisyn/compiler")) {
    return yield* loadWorkflowExport(workflowPath, exportName);
  }

  // Rule 3: .ts source → compile via compileGraph, extract IR directly
  let result;
  try {
    result = compileGraphForRuntime({ roots: [workflowPath], exportName });
  } catch (err) {
    // E-GRAPH-002: selected export not found → exit code 2
    if (err instanceof CompileError && err.code === "E-GRAPH-002") {
      throw new CliError(
        2,
        `Workflow source '${workflowPath}' does not export '${exportName}'. ${err.message}`,
      );
    }
    const msg = err instanceof Error ? err.message : String(err);
    throw new CliError(1, `Failed to compile workflow source '${workflowPath}': ${msg}`);
  }

  return {
    ir: result.ir,
    inputSchema: result.inputSchema,
    runtimeBindings: result.runtimeBindings,
  };
}

/**
 * CLI-specific error with an exit code.
 */
export class CliError extends Error {
  constructor(
    public readonly exitCode: number,
    message: string,
  ) {
    super(message);
    this.name = "CliError";
  }
}
