/**
 * `tsn run` command — config-aware workflow execution.
 *
 * Full startup lifecycle:
 * A. Load and validate descriptor
 * B. Derive and validate inputs from CLI flags
 * C. Resolve environment
 * D. Start resources (journal, transports, server) and execute workflow
 */

import { resolve, dirname, isAbsolute } from "node:path";
import { call, exit, spawn, withResolvers } from "effection";
import type { Operation } from "effection";
import {
  applyOverlay,
  resolveConfig,
  execute,
  ConfigError as RuntimeConfigError,
} from "@tisyn/runtime";
import type { ResolvedConfig } from "@tisyn/runtime";
import {
  loadDescriptorModule,
  resolveWorkflowModule,
  loadWorkflowExport,
  CliError,
} from "./load-descriptor.js";
import { deriveFlags, parseInputFlags } from "./inputs.js";
import { installAllTransports, createJournalStream, startServer } from "./startup.js";
import type { RunCommandOptions } from "./types.js";

export function* runRun(
  options: RunCommandOptions,
  cwd: string,
  extraArgv: string[],
): Operation<void> {
  const modulePath = resolve(cwd, options.module);

  // Phase A: Load and validate descriptor
  const descriptor = yield* call(() => loadDescriptorModule(modulePath));
  const merged = options.entrypoint ? applyOverlay(descriptor, options.entrypoint) : descriptor;

  // Phase B: Derive and validate inputs
  const { modulePath: workflowPath, exportName } = resolveWorkflowModule(merged, modulePath);
  const workflowExport = yield* call(() => loadWorkflowExport(workflowPath, exportName));

  if (!workflowExport.inputSchema) {
    throw new CliError(
      2,
      `Workflow module '${workflowPath}' does not export input schema metadata for '${exportName}'. Ensure the module was generated by a compatible @tisyn/compiler version.`,
    );
  }
  if (workflowExport.inputSchema.type === "unsupported") {
    throw new CliError(
      2,
      `Workflow '${exportName}' has unsupported input parameters: ${workflowExport.inputSchema.reason}. Only zero-parameter or flat-object-parameter workflows are supported.`,
    );
  }

  let inputFlags: FlagInfo = { flags: [], parsed: {} };
  if (workflowExport.inputSchema.type === "object") {
    const flags = deriveFlags(workflowExport.inputSchema);
    if (flags.length > 0) {
      const parsed = parseInputFlags(flags, extraArgv);
      inputFlags = { flags, parsed };
    }
  }

  // Phase C: Resolve environment
  let resolvedProjection;
  try {
    resolvedProjection = resolveConfig(merged, {
      entrypoint: options.entrypoint,
      processEnv: process.env as Record<string, string>,
    });
  } catch (err) {
    if (err instanceof RuntimeConfigError) {
      console.error(`Environment resolution failed:\n${err.message}`);
      yield* exit(5);
      return;
    }
    throw err;
  }

  // Resolve descriptor-relative paths in config
  const descriptorDir = dirname(modulePath);
  rebaseConfigPaths(resolvedProjection, descriptorDir);

  // Phase D: Start resources and execute
  const stream = createJournalStream(resolvedProjection.journal);

  // Install agent transports
  yield* installAllTransports(resolvedProjection);

  // Start server if present and wait for it to be listening
  if (resolvedProjection.server) {
    const serverReady = withResolvers<void>();
    yield* spawn(function* () {
      yield* startServer(resolvedProjection.server!, serverReady.resolve);
    });
    yield* serverReady.operation;
  }

  // Execute workflow
  const { result } = yield* execute({
    ir: workflowExport.ir,
    env: inputFlags.parsed as never,
    config: resolvedProjection as unknown as Record<string, unknown>,
    stream,
  });

  if (result.status === "ok") {
    if (options.verbose && result.value !== null && result.value !== undefined) {
      console.log(JSON.stringify(result.value, null, 2));
    }
  } else if (result.status === "err") {
    console.error(`Workflow execution failed: ${result.error.message}`);
    yield* exit(6);
  } else {
    console.error("Workflow execution was cancelled");
    yield* exit(6);
  }
}

interface FlagInfo {
  flags: ReturnType<typeof deriveFlags>;
  parsed: Record<string, unknown>;
}

/**
 * Resolve all filesystem paths in a ResolvedConfig relative to the descriptor directory.
 * Mutates the config in place.
 */
export function rebaseConfigPaths(config: ResolvedConfig, descriptorDir: string): void {
  const rebase = (p: string) => (isAbsolute(p) ? p : resolve(descriptorDir, p));

  for (const agent of config.agents) {
    const t = agent.transport;
    if ((t.kind === "local" || t.kind === "inprocess") && typeof t.module === "string") {
      t.module = rebase(t.module);
    }
    if (t.kind === "worker" && typeof t.url === "string" && !(t.url as string).includes("://")) {
      t.url = rebase(t.url as string);
    }
    if (
      t.kind === "stdio" &&
      typeof t.command === "string" &&
      (t.command as string).startsWith("./")
    ) {
      t.command = rebase(t.command as string);
    }
  }

  if (config.journal.kind === "file" && typeof config.journal.path === "string") {
    config.journal.path = rebase(config.journal.path);
  }

  if (config.server?.static) {
    config.server.static = rebase(config.server.static);
  }
}
