/**
 * `tsn run` command — config-aware workflow execution.
 *
 * Full startup lifecycle:
 * A. Load and validate descriptor
 * B. Derive and validate inputs from CLI flags
 * C. Resolve environment
 * D. Start resources (journal, transports, server) and execute workflow
 */

import { resolve, dirname, isAbsolute } from "node:path";
import { exit } from "effection";
import type { Operation } from "effection";
import type { Val, FnNode, IrInput } from "@tisyn/ir";
import { Call, Ref, isFnNode } from "@tisyn/ir";
import {
  applyOverlay,
  resolveConfig,
  execute,
  ConfigError as RuntimeConfigError,
} from "@tisyn/runtime";
import type { ResolvedConfig } from "@tisyn/runtime";
import {
  loadDescriptorModule,
  resolveWorkflowModule,
  resolveWorkflowExport,
  loadWorkflowExport,
  CliError,
} from "./load-descriptor.js";
import { deriveFlags, parseInputFlags, formatInputHelp } from "./inputs.js";
import { installAllTransports, createJournalStream, startServer } from "./startup.js";
import type { LocalServerBinding } from "@tisyn/transport";
import type { RunCommandOptions } from "./types.js";

/**
 * Shared Phase A + B: load descriptor, apply entrypoint overlay, resolve
 * workflow module, and load workflow export with input schema.
 *
 * Used by both runRun() and runHelp() so the two paths cannot drift.
 */
function* loadRunMetadata(modulePath: string, entrypoint?: string) {
  // Phase A: Load and validate descriptor
  const descriptor = yield* loadDescriptorModule(modulePath);
  const merged = entrypoint ? applyOverlay(descriptor, entrypoint) : descriptor;

  // Phase B: Resolve workflow module and load/compile export
  const {
    modulePath: workflowPath,
    exportName,
    explicit,
  } = resolveWorkflowModule(merged, modulePath);
  // Non-explicit: descriptor module itself contains exports → load at runtime
  // Explicit: external module → three-step dispatch (compile if authored .ts)
  const workflowExport = explicit
    ? yield* resolveWorkflowExport(workflowPath, exportName)
    : yield* loadWorkflowExport(workflowPath, exportName);

  return { descriptor, merged, workflowPath, exportName, workflowExport };
}

export function* runRun(
  options: RunCommandOptions,
  cwd: string,
  extraArgv: string[],
): Operation<void> {
  const modulePath = resolve(cwd, options.module);
  const { descriptor, workflowPath, exportName, workflowExport } = yield* loadRunMetadata(
    modulePath,
    options.entrypoint,
  );

  if (!workflowExport.inputSchema) {
    throw new CliError(
      2,
      `Workflow module '${workflowPath}' does not export input schema metadata for '${exportName}'. Ensure the module was generated by a compatible @tisyn/compiler version.`,
    );
  }
  if (workflowExport.inputSchema.type === "unsupported") {
    throw new CliError(
      2,
      `Workflow '${exportName}' has unsupported input parameters: ${workflowExport.inputSchema.reason}. Only zero-parameter or flat-object-parameter workflows are supported.`,
    );
  }

  const flags =
    workflowExport.inputSchema.type === "object" ? deriveFlags(workflowExport.inputSchema) : [];
  const parsed = parseInputFlags(flags, extraArgv);
  const inputFlags: FlagInfo = { flags, parsed };

  // Phase C: Resolve environment
  let resolvedProjection;
  try {
    resolvedProjection = resolveConfig(descriptor, {
      entrypoint: options.entrypoint,
      processEnv: process.env as Record<string, string>,
    });
  } catch (err) {
    if (err instanceof RuntimeConfigError) {
      console.error(`Environment resolution failed:\n${err.message}`);
      yield* exit(5);
      return;
    }
    throw err;
  }

  // Resolve descriptor-relative paths in config
  const descriptorDir = dirname(modulePath);
  rebaseConfigPaths(resolvedProjection, descriptorDir);

  // Phase D: Start resources and execute
  const stream = createJournalStream(resolvedProjection.journal);

  // Start server first if present (bindings may need it)
  let serverBinding: LocalServerBinding | undefined;
  if (resolvedProjection.server) {
    try {
      serverBinding = yield* startServer(resolvedProjection.server);
      console.log(`Server listening on http://localhost:${serverBinding.address.port}`);
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      console.error(`Server failed to start: ${msg}`);
      yield* exit(6);
      return;
    }
  }

  // Install agent transports (with server binding if available)
  yield* installAllTransports(resolvedProjection, serverBinding);

  // Auto-invoke bare Fn nodes: the compiler produces Fn(params, body) closures;
  // the kernel would return the closure as a value rather than executing it.
  // Wrap in Call with the correct argument model.
  let executableIr: IrInput;
  let execEnv: Record<string, unknown>;

  if (isFnNode(workflowExport.ir)) {
    const fn = workflowExport.ir as FnNode;
    if (fn.params.length === 0) {
      executableIr = Call(fn);
      execEnv = {};
    } else if (fn.params.length === 1) {
      const paramName = fn.params[0];
      executableIr = Call(fn, Ref(paramName));
      execEnv = { [paramName]: inputFlags.parsed };
    } else {
      throw new CliError(2, "Workflows with multiple parameters are not supported");
    }
  } else {
    executableIr = workflowExport.ir;
    execEnv = inputFlags.parsed;
  }

  // Execute workflow
  const { result } = yield* execute({
    ir: executableIr,
    env: execEnv as never,
    config: resolvedProjection as unknown as Val,
    stream,
  });

  if (result.status === "ok") {
    if (options.verbose && result.value !== null && result.value !== undefined) {
      console.log(JSON.stringify(result.value, null, 2));
    }
  } else if (result.status === "error") {
    console.error(`Workflow execution failed: ${result.error.message}`);
    yield* exit(6);
  } else {
    console.error("Workflow execution was cancelled");
    yield* exit(6);
  }
}

interface FlagInfo {
  flags: ReturnType<typeof deriveFlags>;
  parsed: Record<string, unknown>;
}

const BUILTIN_HELP = `Usage: tsn run <module> [options]

Options:
  --entrypoint <name>, -e    Apply a named entrypoint overlay
  --verbose                  Show detailed diagnostics
  --help, -h                 Show help`;

/**
 * Dynamic help for `tsn run <module> --help`.
 *
 * Loads the descriptor and workflow metadata to show workflow-derived flags
 * and entrypoints alongside built-in options. On failure, shows built-in
 * options plus a diagnostic explaining why workflow flags cannot be shown.
 */
export function* runHelp(options: RunCommandOptions, cwd: string): Operation<void> {
  console.log(BUILTIN_HELP);
  const modulePath = resolve(cwd, options.module);

  try {
    const { descriptor, workflowExport } = yield* loadRunMetadata(modulePath, options.entrypoint);

    if (!workflowExport.inputSchema) {
      console.error(
        "\nCould not show workflow flags: module does not export input schema metadata.",
      );
      yield* exit(2);
      return;
    }

    if (workflowExport.inputSchema.type === "unsupported") {
      console.error(
        `\nCould not show workflow flags: unsupported input parameters (${workflowExport.inputSchema.reason}).`,
      );
      yield* exit(2);
      return;
    }

    if (workflowExport.inputSchema.type === "object") {
      const flags = deriveFlags(workflowExport.inputSchema);
      if (flags.length > 0) {
        console.log(formatInputHelp(flags));
      }
    }

    if (descriptor.entrypoints && Object.keys(descriptor.entrypoints).length > 0) {
      console.log("\nEntrypoints:");
      for (const name of Object.keys(descriptor.entrypoints)) {
        console.log(`  ${name}`);
      }
    }
  } catch (error) {
    const msg = error instanceof Error ? error.message : String(error);
    console.error(`\nCould not load workflow to show dynamic flags: ${msg}`);
    if (error instanceof CliError) {
      yield* exit(error.exitCode);
    } else {
      yield* exit(2);
    }
  }
}

/**
 * Resolve all filesystem paths in a ResolvedConfig relative to the descriptor directory.
 * Mutates the config in place.
 */
export function rebaseConfigPaths(config: ResolvedConfig, descriptorDir: string): void {
  const rebase = (p: string) => (isAbsolute(p) ? p : resolve(descriptorDir, p));

  for (const agent of config.agents) {
    const t = agent.transport;
    if ((t.kind === "local" || t.kind === "inprocess") && typeof t.module === "string") {
      t.module = rebase(t.module);
    }
    if (t.kind === "worker" && typeof t.url === "string" && !(t.url as string).includes("://")) {
      t.url = rebase(t.url as string);
    }
    if (
      t.kind === "stdio" &&
      typeof t.command === "string" &&
      (t.command as string).startsWith("./")
    ) {
      t.command = rebase(t.command as string);
    }
  }

  if (config.journal.kind === "file" && typeof config.journal.path === "string") {
    config.journal.path = rebase(config.journal.path);
  }

  if (config.server?.static) {
    config.server.static = rebase(config.server.static);
  }
}
