// Auto-generated by @tisyn/compiler — do not edit
import { agent, operation } from "@tisyn/agent";
import type { DeclaredAgent, OperationSpec } from "@tisyn/agent";
import type { TisynFn } from "@tisyn/ir";
import { Fn, Ref, Eval, Let, Call, Get, Construct, Arr, ConcatArrays } from "@tisyn/ir";

export function App(): DeclaredAgent<{
  waitForUser: OperationSpec<{ input: { prompt: string } }, { message: string }>;
  showAssistantMessage: OperationSpec<{ input: { message: string } }, void>;
  hydrateTranscript: OperationSpec<
    { input: { messages: Array<{ role: string; content: string }> } },
    void
  >;
  setReadOnly: OperationSpec<{ input: { reason: string } }, void>;
}> {
  const id = "app";
  return agent(id, {
    waitForUser: operation<{ input: { prompt: string } }, { message: string }>(),
    showAssistantMessage: operation<{ input: { message: string } }, void>(),
    hydrateTranscript: operation<
      { input: { messages: Array<{ role: string; content: string }> } },
      void
    >(),
    setReadOnly: operation<{ input: { reason: string } }, void>(),
  });
}

export function Llm(): DeclaredAgent<{
  sample: OperationSpec<
    {
      input: {
        history: Array<{ role: string; content: string }>;
        message: string;
      };
    },
    { message: string }
  >;
}> {
  const id = "llm";
  return agent(id, {
    sample: operation<
      {
        input: {
          history: Array<{ role: string; content: string }>;
          message: string;
        };
      },
      { message: string }
    >(),
  });
}

export const chat: TisynFn<[], unknown> = Fn(
  [],
  Let(
    "history_0",
    Arr(),
    Let(
      "__loop_0",
      Fn(
        ["history_0"],
        Let(
          "user",
          Eval(
            "app.waitForUser",
            Construct({
              input: Construct({
                prompt: "Say something",
              }),
            }),
          ),
          Let(
            "assistant",
            Eval(
              "llm.sample",
              Construct({
                input: Construct({
                  history: Ref("history_0"),
                  message: Get(Ref("user"), "message"),
                }),
              }),
            ),
            Let(
              "history_1",
              ConcatArrays(
                Ref("history_0"),
                Arr(
                  Construct({
                    role: "user",
                    content: Get(Ref("user"), "message"),
                  }),
                  Construct({
                    role: "assistant",
                    content: Get(Ref("assistant"), "message"),
                  }),
                ),
              ),
              Let(
                "__discard_0",
                Eval(
                  "app.showAssistantMessage",
                  Construct({
                    input: Construct({
                      message: Get(Ref("assistant"), "message"),
                    }),
                  }),
                ),
                Call(Ref("__loop_0"), Ref("history_1")),
              ),
            ),
          ),
        ),
      ),
      Call(Ref("__loop_0"), Ref("history_0")),
    ),
  ),
);

export const agents = { App, Llm };
export const workflows = { chat };
