// Auto-generated by @tisyn/compiler — do not edit
import { agent, operation } from "@tisyn/agent";
import type { DeclaredAgent, OperationSpec } from "@tisyn/agent";
import type { TisynFn } from "@tisyn/ir";
import {
  Fn,
  Ref,
  Eval,
  Let,
  If,
  Call,
  Get,
  Eq,
  Construct,
  Concat,
  Try,
  Resource,
  Provide,
} from "@tisyn/ir";
import type { SessionHandle, PromptResult, NewSessionConfig, PromptArgs } from "@tisyn/code-agent";

export function Claude(): DeclaredAgent<{
  newSession: OperationSpec<NewSessionConfig, SessionHandle>;
  closeSession: OperationSpec<SessionHandle, null>;
  prompt: OperationSpec<PromptArgs, PromptResult>;
}> {
  const id = "claude";
  return agent(id, {
    newSession: operation<NewSessionConfig, SessionHandle>(),
    closeSession: operation<SessionHandle, null>(),
    prompt: operation<PromptArgs, PromptResult>(),
  });
}

export function Codex(): DeclaredAgent<{
  newSession: OperationSpec<NewSessionConfig, SessionHandle>;
  closeSession: OperationSpec<SessionHandle, null>;
  prompt: OperationSpec<PromptArgs, PromptResult>;
}> {
  const id = "codex";
  return agent(id, {
    newSession: operation<NewSessionConfig, SessionHandle>(),
    closeSession: operation<SessionHandle, null>(),
    prompt: operation<PromptArgs, PromptResult>(),
  });
}

export function Output(): DeclaredAgent<{
  log: OperationSpec<{ label: string; text: string }, void>;
}> {
  const id = "output";
  return agent(id, {
    log: operation<{ label: string; text: string }, void>(),
  });
}

export const handoff: TisynFn<[{ task: string }], unknown> = Fn(
  ["input"],
  Let(
    "__discard_0",
    Eval(
      "output.log",
      Construct({
        label: "Task",
        text: Get(Ref<any>("input"), "task"),
      }),
    ),
    Let(
      "__discard_1",
      Eval(
        "output.log",
        Construct({
          label: "Status",
          text: "Opening Claude session...",
        }),
      ),
      Let(
        "claudeSession",
        Call(
          Ref<any>("useClaudeSession"),
          Construct({
            model: "claude-sonnet-4-6",
          }),
        ),
        Let(
          "__discard_2",
          Eval(
            "output.log",
            Construct({
              label: "Status",
              text: "Requesting Claude analysis...",
            }),
          ),
          Let(
            "claudeResult",
            Eval(
              "claude.prompt",
              Construct({
                session: Ref<any>("claudeSession"),
                prompt: Concat(
                  "Reply to the other agent in one short message. Do not run tools or commands.\n\nUser request: ",
                  Get(Ref<any>("input"), "task"),
                ),
              }),
            ),
            Let(
              "__discard_3",
              Eval(
                "output.log",
                Construct({
                  label: "Claude",
                  text: Get(Ref<any>("claudeResult"), "response"),
                }),
              ),
              If(
                Eq(Get(Ref<any>("claudeResult"), "response"), ""),
                Let(
                  "__discard_4",
                  Eval(
                    "output.log",
                    Construct({
                      label: "Status",
                      text: "Skipping Codex handoff because Claude did not return usable analysis.",
                    }),
                  ),
                  null,
                ),
                Let(
                  "__discard_5",
                  Eval(
                    "output.log",
                    Construct({
                      label: "Status",
                      text: "Opening Codex session...",
                    }),
                  ),
                  Let(
                    "codexSession",
                    Call(Ref<any>("useCodexSession"), Construct({})),
                    Let(
                      "__discard_6",
                      Eval(
                        "output.log",
                        Construct({
                          label: "Status",
                          text: "Handing Claude message to Codex for a brief reply...",
                        }),
                      ),
                      Let(
                        "codexResult",
                        Eval(
                          "codex.prompt",
                          Construct({
                            session: Ref<any>("codexSession"),
                            prompt: Concat(
                              "Hello, Codex. Reply to Claude with exactly one short greeting sentence. Do not inspect files, run commands, or suggest next steps.\n\nClaude's message:\n",
                              Get(Ref<any>("claudeResult"), "response"),
                            ),
                          }),
                        ),
                        Let(
                          "__discard_7",
                          Eval(
                            "output.log",
                            Construct({
                              label: "Codex",
                              text: Get(Ref<any>("codexResult"), "response"),
                            }),
                          ),
                          Eval(
                            "output.log",
                            Construct({
                              label: "Status",
                              text: "Workflow complete.",
                            }),
                          ),
                        ),
                      ),
                    ),
                  ),
                ),
              ),
            ),
          ),
        ),
      ),
    ),
  ),
);

const __m0_useCodexSession: TisynFn<[NewSessionConfig], unknown> = Fn(
  ["config"],
  Resource(
    Let(
      "handle",
      Eval("codex.newSession", Ref<any>("config")),
      Try(
        Provide(Ref<any>("handle")),
        undefined,
        undefined,
        Eval("codex.closeSession", Ref<any>("handle")),
      ),
    ),
  ),
);

const __m0_useClaudeSession: TisynFn<[NewSessionConfig], unknown> = Fn(
  ["config"],
  Resource(
    Let(
      "handle",
      Eval("claude.newSession", Ref<any>("config")),
      Try(
        Provide(Ref<any>("handle")),
        undefined,
        undefined,
        Eval("claude.closeSession", Ref<any>("handle")),
      ),
    ),
  ),
);

export const agents = { Claude, Codex, Output };
export const workflows = { handoff };

export const inputSchemas = {
  handoff: { fields: [{ fieldType: "string", name: "task", optional: false }], type: "object" },
};
